### ISSUE TITLE
Transform operation fails at runtime with "unable to load custom token provider class" error message

### ISSUE THREAD

**Issue by PAOLT** [opencb/opencga#1107]
When performing a transform operation from the client VM a run time exception is returned:

`Unable to load custom token provider class.
        at org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getTokenProvider(AbfsConfiguration.java:531)
        at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:882)
        at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:181)
        at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:108)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2796)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2830)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2812)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:390)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:179)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:374)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.initTempDir(DynamicClassLoader.java:118)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:98)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:251)
        at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:75)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:903)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:648)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at org.opencb.opencga.storage.hadoop.utils.HBaseManager.getConnection(HBaseManager.java:125)
        at org.opencb.opencga.storage.hadoop.utils.HBaseManager.<init>(HBaseManager.java:79)
        at org.opencb.opencga.storage.hadoop.variant.metadata.AbstractHBaseDBAdaptor.<init>(AbstractHBaseDBAdaptor.java:48)
        at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseProjectMetadataDBAdaptor.<init>(HBaseProjectMetadataDBAdaptor.java:46)
        at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseVariantStorageMetadataDBAdaptorFactory.buildProjectMetadataDBAdaptor(HBaseVariantStorageMetadataDBAdaptorFactory.java:38)
        at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseVariantStorageMetadataDBAdaptorFactory.buildProjectMetadataDBAdaptor(HBaseVariantStorageMetadataDBAdaptorFactory.java:13)
        at org.opencb.opencga.storage.core.metadata.StudyConfigurationManager.<init>(StudyConfigurationManager.java:76)
        at org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine.getStudyConfigurationManager(HadoopVariantStorageEngine.java:923)
        at org.opencb.opencga.storage.core.manager.variant.operations.StorageOperation.updateCatalogFromStudyConfiguration(StorageOperation.java:117)
        at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.index(VariantFileIndexerStorageOperation.java:160)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:181)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:172)
        at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:303)
        at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:115)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
`

**Comment by PAOLT** [comment]
`#install catalog (remember password for later use)
sudo /opt/opencga/bin/opencga-admin.sh catalog install --secret-key SeCrEtKeY
## TESTING WITH TEST VCF FILE FROM DOWN HERE

# start daemon (for debugging) in a seperate terminal:
sudo /opt/opencga/bin/opencga-admin.sh catalog daemon --start

# create user (in new seperate terminal)
sudo /opt/opencga/bin/opencga-admin.sh users create -u bart --email test@gel.ac.uk --name "John Doe" --user-password testpwd

# login to get session token (replace bart with your newly created user)
sudo /opt/opencga/bin/opencga.sh users login -u bart

# create project
sudo /opt/opencga/bin/opencga.sh projects create --id reference_grch37 -n "Reference studies GRCh37" --organism-scientific-name "Homo sapiens" --organism-assembly "GRCh37"

# create study within your project
sudo /opt/opencga/bin/opencga.sh studies create --id 1kG_phase3 -n "1000 Genomes Project - Phase 3" --project reference_grch37

#wget vcf genome file
wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

#link vcf genome file (with absolute path to vcf file). todo: replace /home/bart/ with your path
sudo /opt/opencga/bin/opencga.sh files link -i /home/bart/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz -s 1kG_phase3

#index: transform/load/annotate
#transform -> view progress in DAEMON terminal
sudo /opt/opencga/bin/opencga.sh variant index --file ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --transform -o outDir
#load -> view progress in DAEMON terminal
sudo /opt/opencga/bin/opencga.sh variant index --file ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --load -o outDir

#query:
sudo /opt/opencga/bin/opencga-analysis.sh variant query --sample HG00096 --limit 100`

**Comment by PAOLT** [comment]
### Solution

If the file is already linked and loaded, the transform fails with the above exception. Re-linking the file with a different name solved the problem.
