### ISSUE TITLE
Export tool fails with  java.lang.NoSuchMethodError exception 

### ISSUE THREAD

**Issue by PAOLT** [opencb/opencga#1108]
### Exception  thrown

`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.avro.Schema$Parser.parse(Ljava/lang/String;[Ljava/lang/String;)Lorg/apache/avro/Schema;
        at org.opencb.biodata.models.variant.avro.VariantAvro.<clinit>(VariantAvro.java:10)
        at org.opencb.opencga.storage.hadoop.variant.io.VariantExporterDriver.setupJob(VariantExporterDriver.java:148)
        at org.opencb.opencga.storage.hadoop.variant.AbstractVariantsTableDriver.setupJob(AbstractVariantsTableDriver.java:146)
        at org.opencb.opencga.storage.hadoop.utils.AbstractHBaseDriver.run(AbstractHBaseDriver.java:97)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
        at org.opencb.opencga.storage.hadoop.variant.io.VariantExporterDriver.main(VariantExporterDriver.java:217)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:243)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
`

**Comment by PAOLT** [comment]
### Context
After having transformed and loaded a VCF file, run the export tool from the HDI's head node

### Code

#### export statements
`export HADOOP_USER_CLASSPATH_FIRST=true
hbase_conf=$(hbase classpath | tr ":" "\n" | grep "/conf" | tr "\n" ":")
export HADOOP_CLASSPATH=${hbase_conf}:$PWD/libs/avro-1.7.7.jar:$PWD/libs/jackson-databind-2.6.6.jar:$PWD/libs/jackson-core-2.6.6.jar
export HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$PWD/libs/jackson-annotations-2.6.6.jar`

#### run the tool
`yarn jar ~/opencga/opencga-storage-hadoop-core-1.4.0-rc3-dev-jar-with-dependencies.jar org.opencb.opencga.storage.hadoop.variant.io.VariantExporterDriver opencga_bart_reference_grch37_variants study bart@reference_grch37:1kG_phase3 --of parquet_gz --output my.variants.parquet2`

**Comment by PAOLT** [comment]
### Export tool location

[link](https://github.com/opencb/opencga/blob/develop/opencga-storage/opencga-storage-hadoop/opencga-storage-hadoop-core/src/main/java/org/opencb/opencga/storage/hadoop/variant/io/VariantExporterDriver.java)

**Comment by j-coll** [comment]
I have followed your instructions, and I was not able to reproduce the error. 
Did you do anything else apart from this?

The export commands are dependant on the working directory ($PWD)
Where you located in the opencga directory when executing that command?

**Comment by PAOLT** [comment]
Hi Jacobo
Thought about it a bit and I am pretty sure I didn't cd to opencb before running the export statements.
Paolo

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by PAOLT** [comment]
### Solution

Ensure to execute `cd opencga` before running the export command
