### ISSUE TITLE
NumberFormatException when exporting VCF with empty contig length

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1130]
Reported by @javild 

```
Caused by: java.lang.NumberFormatException: For input string: "null"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at htsjdk.variant.vcf.VCFContigHeaderLine.getSAMSequenceRecord(VCFContigHeaderLine.java:81)
        at htsjdk.variant.vcf.VCFHeader.getSequenceDictionary(VCFHeader.java:205)
        at org.opencb.opencga.storage.core.variant.io.VcfDataWriter.pre(VcfDataWriter.java:81)
        at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:414)
        at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:391)
        at org.opencb.opencga.storage.core.variant.io.VariantExporter.exportData(VariantExporter.java:141)
        at org.opencb.opencga.storage.core.variant.io.VariantExporter.export(VariantExporter.java:90)
        at org.opencb.opencga.storage.core.variant.VariantStorageEngine.exportData(VariantStorageEngine.java:260)
        at org.opencb.opencga.storage.core.manager.variant.operations.VariantExportStorageOperation.exportData(VariantExportStorageOperation.java:139)
        ... 5 more
```

**Comment by j-coll** [comment]
https://github.com/opencb/biodata/commit/295c8a87bbd7d4a01e52e3836716b347f53e61c3
