### ISSUE TITLE
Create CellBase Docker image.

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1209]
Related to #1105

**Comment by marrobi** [comment]
WIP here: https://github.com/marrobi/cellbase/tree/feature-docker

Need assistance configuring cellbase and mongodb

**Comment by marrobi** [comment]
Requires Mongo DB SSL support to be added to cellbase. @j-coll to add.

**Comment by marrobi** [comment]
Waiting on https://github.com/opencb/cellbase/pull/390

**Comment by marrobi** [comment]
Strugglign to connect, using the branch with SSL, and configuration.json as below:

```
"mongodb": {
                        "host": "cgamongofatyosscyniqo0.uksouth.cloudapp.azure.com:27017,cgamongofatyosscyniqo1.uksouth.cloudapp.azure.com:27017,cgamongofatyosscyniqo2.uksouth.cloudapp.azure.com"
                        "user": "opencgaadmin",
                        "password": "xxxx",
                        "options": {
                                "authenticationDatabase": "admin",
                                "readPreference": "nearest",
                                "replicaSet": "",
                                "connectionsPerHost": 20
                                "sslEnabled": true
                        }
                },
```

Any ideas how I can see what's going wrong? Deployment is here: http://52.178.99.41:8080/cellbase/webservices/

**Comment by marrobi** [comment]
Ah, get 

'''
019-03-18 11:43:20 [http-nio-8080-exec-9] ERROR ReflectionUtils:24 - Failed to resolve 'list of strings' into class
java.lang.ClassNotFoundException: list of strings
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
        at io.swagger.util.ReflectionUtils.loadClassByName(ReflectionUtils.java:44)
        at io.swagger.util.ReflectionUtils.typeFromString(ReflectionUtils.java:22)
        at io.swagger.jaxrs.Reader.readImplicitParam(Reader.java:438)
        at io.swagger.jaxrs.Reader.readImplicitParameters(Reader.java:414)
        at io.swagger.jaxrs.Reader.read(Reader.java:401)
        at io.swagger.jaxrs.Reader.read(Reader.java:150)
        at io.swagger.jaxrs.listing.BaseApiListingResource.scan(BaseApiListingResource.java:63)
        at io.swagger.jaxrs.listing.BaseApiListingResource.process(BaseApiListingResource.java:120)
        at io.swagger.jaxrs.listing.BaseApiListingResource.getListingJsonResponse(BaseApiListingResource.java:165)
        at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.opencb.cellbase.server.ws.CORSFilter.doFilter(CORSFilter.java:31)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
'''

**Comment by marrobi** [comment]
Draft PR is here: https://github.com/opencb/cellbase/pull/393

I'm in meetings for the rest of the week. @lawrencegripper if you or someone else in the team has time to pick this up please do. Not sure if need multiple images as we have done with opencga dockerfiles, or should download a release. Also needs a jenkinsfile.

**Comment by marrobi** [comment]
This PR is now awaiting review in the cellbase repo.

**Comment by lawrencegripper** [comment]
@marrobi added some comments now

**Comment by marrobi** [comment]
Merged and image on Docker Hub.
