### ISSUE TITLE
Fix SQLException parsing wrong SampleIndex RowKeys

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1217]
#### Exception
```
java.lang.RuntimeException: java.sql.SQLException: ERROR 201 (22000): Illegal data. Expected length of at least 4 bytes, but had 3
        at org.apache.phoenix.schema.types.PDataType.checkForSufficientLength(PDataType.java:274)
        at org.apache.phoenix.schema.types.PInteger$IntCodec.decodeInt(PInteger.java:183)
        at org.apache.phoenix.schema.types.PInteger.toObject(PInteger.java:81)
        at org.apache.phoenix.schema.types.PInteger.toObject(PInteger.java:28)
        at org.apache.phoenix.schema.types.PDataType.toObject(PDataType.java:980)
        at org.apache.phoenix.schema.types.PDataType.toObject(PDataType.java:984)
        at org.apache.phoenix.schema.types.PDataType.toObject(PDataType.java:1013)
        at org.opencb.opencga.storage.hadoop.variant.index.sample.HBaseToSampleIndexConverter.rowKeyToString(HBaseToSampleIndexConverter.java:127)
        at org.opencb.opencga.storage.hadoop.variant.index.sample.SampleIndexDBAdaptor.parse(SampleIndexDBAdaptor.java:343)

```

#### Description
Read sample id 256
HBase scan with "rowPrefix = 0x000000FF"

This is translated in
startRow: 00-00-00-FF
stopRow: 00-00-01 (trimming trailing 00) 

The error happens when trying to read the starting 4 bytes from the startRow and stopRow as an integer. For the stopRow, it founds 3 instead of 4 bytes,

**Comment by j-coll** [comment]
Fixed at 70a1a94ef8f57f72e1ba16ec0be61f426b6fe3b4
