### ISSUE TITLE
Annotate step in Getting Started in 5 minutes

### ISSUE THREAD

**Issue by bokhariy** [opencb/opencga#1223]
I have the following error when I execute this step
./opencga-analysis.sh variant annotate -s 1kG_phase3 -o /tmp/temporal_annotation

019-03-25 07:39:31 [main] INFO  AbstractCellBaseVariantAnnotator:63 - Annotating with Cellbase REST. host 'http://bioinfo.hpc.cam.ac.uk/cellbase/', version 'v4', species 'hsapiens', assembly 'GRCh37'
2019-03-25 07:39:31 [main] ERROR VariantAnnotationStorageOperation:177 - Error annotating variants.
org.opencb.opencga.storage.core.variant.adaptors.VariantQueryException: Study { name: "test@reference_grch37:1kG_phase3" } not found.
	at org.opencb.opencga.storage.core.variant.adaptors.VariantQueryException.studyNotFound(VariantQueryException.java:103)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.getStudyId(VariantStorageMetadataManager.java:352)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.getStudyIds(VariantStorageMetadataManager.java:322)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.getStudyIds(VariantStorageMetadataManager.java:303)
	at org.opencb.opencga.storage.core.variant.adaptors.VariantQueryUtils.getIncludeStudies(VariantQueryUtils.java:631)
	at org.opencb.opencga.storage.core.variant.adaptors.VariantQueryUtils.getIncludeStudies(VariantQueryUtils.java:600)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.preAnnotate(DefaultVariantAnnotationManager.java:378)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:117)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:370)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:166)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:267)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:388)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:127)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:102)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:35)
org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error annotating variants.
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:179)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:267)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:388)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:127)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:102)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:35)
Caused by: org.opencb.opencga.storage.core.variant.adaptors.VariantQueryException: Study { name: "test@reference_grch37:1kG_phase3" } not found.
	at org.opencb.opencga.storage.core.variant.adaptors.VariantQueryException.studyNotFound(VariantQueryException.java:103)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.getStudyId(VariantStorageMetadataManager.java:352)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.getStudyIds(VariantStorageMetadataManager.java:322)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.getStudyIds(VariantStorageMetadataManager.java:303)
	at org.opencb.opencga.storage.core.variant.adaptors.VariantQueryUtils.getIncludeStudies(VariantQueryUtils.java:631)
	at org.opencb.opencga.storage.core.variant.adaptors.VariantQueryUtils.getIncludeStudies(VariantQueryUtils.java:600)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.preAnnotate(DefaultVariantAnnotationManager.java:378)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:117)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:370)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:166)
	... 5 more

**Comment by j-coll** [comment]
Hi @bokhariy , sorry for the late response

You are talking about the [Getting started in 5 minutes tutorial](http://docs.opencb.org/display/opencga/Getting+Started+in+5+minutes), right?

Most probably, you started the annotate step (using opencga-analysis, which is a synchronous CLI) before the index step finished (probably using opencga.sh, which is an asynchronous CLI).

Could you confirm me this?
I will modify the tutorial to make more clear this point.
