### ISSUE TITLE
Fail to login if user home folder does not exist

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1224]
```
opencga@host:/opt/opencga/bin$ ./opencga.sh users login -u opencga
User password:
java.nio.file.NoSuchFileException: /home/opencga/.opencga
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at org.opencb.opencga.app.cli.CommandExecutor.saveCliSessionFile(CommandExecutor.java:306)
        at org.opencb.opencga.app.cli.main.executors.catalog.UserCommandExecutor.login(UserCommandExecutor.java:128)
        at org.opencb.opencga.app.cli.main.executors.catalog.UserCommandExecutor.execute(UserCommandExecutor.java:89)
        at org.opencb.opencga.app.cli.main.OpencgaMain.main(OpencgaMain.java:146)
```

**Comment by pfurio** [comment]
We should definitely control that scenario, but maybe we should be more flexible and, in those cases, show a warning message so the user is well aware that we will not be able to store the token once they are logged in and inform that they will need to provide that token with every new command line they might run afterwards.
