### ISSUE TITLE
LDAP authentication fails with ldaps server

### ISSUE THREAD

**Issue by ameynert** [opencb/opencga#1257]
I want to use my university's LDAP server (anonymized below as authorise.uni.ac.uk) for OpenCGA authentication. The LDAP server is accessed via ldaps protocol on port 636. It appears that the URL is not being correctly parsed - it comes out as '/authorise.uni.ac.uk' instead of 'authorise.uni.ac.uk' in the error messages. When I use ldap:// instead of ldaps:// the host name is correctly identified, but won't connect as it's the wrong port/protocol combination.

configuration.yml:
```
authentication:
  # Session expiration time in seconds
  expiration: 3600
# LDAP configuration example
  authenticationOrigins:
  - id: UNI_LDAP            # Any id
    type: LDAP
    host: ldaps://authorise.uni.ac.uk:636
    options:
      usersSearch: dc=authorise,dc=uni,dc=ac,dc=uk # Base search to look for the users
      groupsSearch: ou=people,ou=central,dc=authorise,dc=uni,dc=ac,dc=uk # Base search to look for the groups
```
Error:
```
[opencga@server conf]$ opencga-admin.sh users import --auth-origin UNI_LDAP -u ameyner2
Admin password: 
2019-04-15 20:31:01 [main] ERROR LDAPAuthenticationManager:93 - Invalid name: /authorise.uni.ac.uk:636
javax.naming.InvalidNameException: Invalid name: /authorise.uni.ac.uk:636
	at javax.naming.ldap.Rfc2253Parser.parseAttrType(Rfc2253Parser.java:155)
	at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:108)
	at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
	at javax.naming.ldap.LdapName.parse(LdapName.java:785)
	at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
	at com.sun.jndi.ldap.LdapNameParser.parse(LdapNameParser.java:39)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:302)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getDirContext(LDAPUtils.java:48)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getUserInfoFromLDAP(LDAPUtils.java:144)
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.authenticate(LDAPAuthenticationManager.java:74)
	at org.opencb.opencga.catalog.managers.UserManager.login(UserManager.java:506)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.importUsersAndGroups(UsersCommandExecutor.java:133)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.execute(UsersCommandExecutor.java:61)
	at org.opencb.opencga.app.cli.admin.AdminMain.main(AdminMain.java:129)
2019-04-15 20:31:01 [main] INFO  UserManager:331 - Fetching user information from authentication origin 'UNI_LDAP'
2019-04-15 20:31:04 [main] ERROR LDAPAuthenticationManager:121 - Could not retrieve user information Invalid name: /authorise.uni.ac.uk:636
{}
javax.naming.InvalidNameException: Invalid name: /authorise.uni.ac.uk:636
	at javax.naming.ldap.Rfc2253Parser.parseAttrType(Rfc2253Parser.java:155)
	at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:108)
	at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
	at javax.naming.ldap.LdapName.parse(LdapName.java:785)
	at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
	at com.sun.jndi.ldap.LdapNameParser.parse(LdapNameParser.java:39)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:302)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getDirContext(LDAPUtils.java:48)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getUserInfoFromLDAP(LDAPUtils.java:144)
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.getRemoteUserInformation(LDAPAuthenticationManager.java:119)
	at org.opencb.opencga.catalog.managers.UserManager.importRemoteUsers(UserManager.java:333)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.importUsersAndGroups(UsersCommandExecutor.java:136)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.execute(UsersCommandExecutor.java:61)
	at org.opencb.opencga.app.cli.admin.AdminMain.main(AdminMain.java:129)
org.opencb.opencga.catalog.exceptions.CatalogException: Could not retrieve user information
Invalid name: /authorise.uni.ac.uk:636
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.getRemoteUserInformation(LDAPAuthenticationManager.java:122)
	at org.opencb.opencga.catalog.managers.UserManager.importRemoteUsers(UserManager.java:333)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.importUsersAndGroups(UsersCommandExecutor.java:136)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.execute(UsersCommandExecutor.java:61)
	at org.opencb.opencga.app.cli.admin.AdminMain.main(AdminMain.java:129)
Caused by: javax.naming.InvalidNameException: Invalid name: /authorise.uni.ac.uk:636
	at javax.naming.ldap.Rfc2253Parser.parseAttrType(Rfc2253Parser.java:155)
	at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:108)
	at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
	at javax.naming.ldap.LdapName.parse(LdapName.java:785)
	at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
	at com.sun.jndi.ldap.LdapNameParser.parse(LdapNameParser.java:39)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:302)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getDirContext(LDAPUtils.java:48)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getUserInfoFromLDAP(LDAPUtils.java:144)
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.getRemoteUserInformation(LDAPAuthenticationManager.java:119)
	... 4 more
```

**Comment by pfurio** [comment]
Thanks for the report. That must be because your LDAP server works over SSL which is not yet supported. We will have a look to see if we can support it soon.
