### ISSUE TITLE
Exception executing load: Error executing direct load

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1261]
Hi Team,

We are getting below exception while loading the file. 

org.opencb.opencga.storage.core.exceptions.StoragePipelineException: Exception executing load: Error executing direct load

**Comment by Mohammedhusen** [comment]
MongoDBVariantMergeLoader:336 - Missing Variant ' 3:  26043278::<CN0>'
2019-04-24 13:43:15 [pool-1-thread-7] ERROR MongoDBVariantMergeLoader:336 - Missing Variant ' 3:  26043278::<CN2>'
2019-04-24 13:43:15 [pool-1-thread-7] ERROR ParallelTaskRunner:746 - Error writing batch 476676
java.lang.RuntimeException: Missing Variant for update : ' 3:  26043278::<CN0>', ' 3:  26043278::<CN2>', 
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.onUpdateError(MongoDBVariantMergeLoader.java:339)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.updateStage(MongoDBVariantMergeLoader.java:203)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.executeMongoDBOperations(MongoDBVariantMergeLoader.java:159)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.write(MongoDBVariantMergeLoader.java:126)
	at org.opencb.commons.io.DataWriter.write(DataWriter.java:49)
	at org.opencb.opencga.storage.mongodb.variant.load.direct.MongoDBVariantDirectLoader.write(MongoDBVariantDirectLoader.java:75)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:744)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:727)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-24 13:43:15 [pool-1-thread-7] WARN  ParallelTaskRunner:752 - Abort writing thread on fail
2019-04-24 13:43:15 [pool-1-thread-3] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-04-24 13:43:15 [main] WARN  ParallelTaskRunner:538 - Abort read thread on fail
2019-04-24 13:43:15 [pool-1-thread-1] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-04-24 13:43:15 [pool-1-thread-6] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-04-24 13:43:15 [pool-1-thread-5] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-04-24 13:43:15 [pool-1-thread-2] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-04-24 13:43:15 [main] INFO  VariantMongoDBAdaptor:1014 - Start creating indexes
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:418 - read:  timeReading                  = 24080.250s
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:419 - read:  timeBlockedAtPutRead         = 18.471s
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:420 - task;  timeBlockedAtTakeRead        = 63475.615s(total)   ~10579.269s/thread
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:424 - task;  timeTaskApply                = 80974.200s(total)   ~13495.700s/thread
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:428 - task;  timeBlockedAtPutWrite        = 150.173s(total)   ~25.028s/thread
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:430 - write: timeBlockedWatingDataToWrite = 3326.682s
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:431 - write: timeWriting                  = 20773.257s
2019-04-24 13:43:15 [main] INFO  ParallelTaskRunner:434 - total:                              = 24100.747s
2019-04-24 13:43:15 [main] ERROR VariantFileIndexerStorageOperation:287 - Error executing LOAD
org.opencb.opencga.storage.core.exceptions.StoragePipelineException: Exception executing load: Error executing direct load
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine.index(MongoDBVariantStorageEngine.java:398)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.index(VariantFileIndexerStorageOperation.java:285)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:176)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:167)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:274)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:103)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
Caused by: org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error executing direct load
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStoragePipeline.directLoad(MongoDBVariantStoragePipeline.java:355)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine.index(MongoDBVariantStorageEngine.java:340)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: Error while running ParallelTaskRunner. Found 1 exceptions.
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:438)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStoragePipeline.directLoad(MongoDBVariantStoragePipeline.java:332)
	... 8 more
Caused by: java.lang.RuntimeException: Missing Variant for update : ' 3:  26043278::<CN0>', ' 3:  26043278::<CN2>', 
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.onUpdateError(MongoDBVariantMergeLoader.java:339)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.updateStage(MongoDBVariantMergeLoader.java:203)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.executeMongoDBOperations(MongoDBVariantMergeLoader.java:159)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.write(MongoDBVariantMergeLoader.java:126)
	at org.opencb.commons.io.DataWriter.write(DataWriter.java:49)
	at org.opencb.opencga.storage.mongodb.variant.load.direct.MongoDBVariantDirectLoader.write(MongoDBVariantDirectLoader.java:75)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:744)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:727)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by j-coll** [comment]
Hi @Mohammedhusen , could you please describe the actions that you executed before getting into this scenario?

**Comment by Mohammedhusen** [comment]
Hi,

we have run the transformation step and during the loading step getting this error.

**Comment by j-coll** [comment]
Was this the first file to be loaded in the study or in the project?

**Comment by Mohammedhusen** [comment]
Hi j-coll,

Any update on this issue?

We tried to remove lock from studies collection next file loading fine but there is a mismatch in variants count since it is counting from the stage_study collection which is created recently.

Is there another way can solve this issue?

Your urgent response is highly appreciated.
