### ISSUE TITLE
annotation error-java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1278]
Hi Team,

We are getting below error while annotating is another solution to process the huge file.
This is happing in the annotation step.

Exception message: java.io.IOException: Premature EOF
2019-05-11 16:11:25 [pool-2-thread-1] INFO  VariantClient:308 - Re-attempting to solve the query - trying to identify any problematic id to skip it
2019-05-11 16:13:45 [pool-2-thread-9] WARN  ParallelTaskRunner:761 - Catch InterruptedException 
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.getBatch(ParallelTaskRunner.java:791)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:758)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:727)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-11 16:13:45 [main] ERROR VariantAnnotationStorageOperation:174 - Error annotating variants.
org.opencb.opencga.storage.core.variant.annotation.VariantAnnotatorException: Error creating annotations
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:209)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:115)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:316)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:163)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:239)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:351)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:112)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.opencb.commons.run.ParallelTaskRunner.isJobsRunning(ParallelTaskRunner.java:564)
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:525)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:341)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:207)
	... 8 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at org.opencb.commons.datastore.core.QueryResponse.toString(QueryResponse.java:128)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.opencb.cellbase.client.rest.ParentRestClient.fetchData(ParentRestClient.java:241)
	at org.opencb.cellbase.client.rest.ParentRestClient.execute(ParentRestClient.java:142)
	at org.opencb.cellbase.client.rest.VariantClient.getAnnotations(VariantClient.java:37)
	at org.opencb.opencga.storage.core.variant.annotation.annotators.CellBaseRestVariantAnnotator.annotateFiltered(CellBaseRestVariantAnnotator.java:82)
	at org.opencb.opencga.storage.core.variant.annotation.annotators.AbstractCellBaseVariantAnnotator.annotate(AbstractCellBaseVariantAnnotator.java:101)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.lambda$createAnnotation$2(DefaultVariantAnnotationManager.java:183)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager$$Lambda$41/888611662.apply(Unknown Source)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error annotating variants.
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:176)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:239)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:351)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:112)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
Caused by: org.opencb.opencga.storage.core.variant.annotation.VariantAnnotatorException: Error creating annotations
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:209)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:115)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:316)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:163)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.opencb.commons.run.ParallelTaskRunner.isJobsRunning(ParallelTaskRunner.java:564)
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:525)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:341)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:207)
	... 8 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at org.opencb.commons.datastore.core.QueryResponse.toString(QueryResponse.java:128)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.opencb.cellbase.client.rest.ParentRestClient.fetchData(ParentRestClient.java:241)
	at org.opencb.cellbase.client.rest.ParentRestClient.execute(ParentRestClient.java:142)
	at org.opencb.cellbase.client.rest.VariantClient.getAnnotations(VariantClient.java:37)
	at org.opencb.opencga.storage.core.variant.annotation.annotators.CellBaseRestVariantAnnotator.annotateFiltered(CellBaseRestVariantAnnotator.java:82)
	at org.opencb.opencga.storage.core.variant.annotation.annotators.AbstractCellBaseVariantAnnotator.annotate(AbstractCellBaseVariantAnnotator.java:101)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.lambda$createAnnotation$2(DefaultVariantAnnotationManager.java:183)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager$$Lambda$41/888611662.apply(Unknown Source)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor

**Comment by j-coll** [comment]
Could you please specify the version being used?

just run `opencga.sh --version` and paste here the output

**Comment by Mohammedhusen** [comment]
Version 1.4.0-dev
Git version: 1.3.5 0cfdeb311f525c5f9f3686e574509c3c12829b5f

**Comment by imedina** [comment]
Not sure if this is related but we increased the memory of the analysis CLI about one month ago:

https://github.com/opencb/opencga/commit/08d38f98b835828d482df7677786f18e9ea83bc0

Could upgrade to latest 1.4.1 and check again? Alos, we are releasing 1.4.2 this week with many fixes and improvements.
