### ISSUE TITLE
java.util.concurrent.TimeoutException: Queue got stuck with 16 items!!!

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1284]
Hi Team,

We getting below error while annotating in both 1.4.0 and 1.4.1 version.

Could you please help resolve this issue as earliest.

2019-05-14 22:36:56 [main] WARN  ParallelTaskRunner:357 - Catch interrupted exception!
java.util.concurrent.TimeoutException: Queue got stuck with 16 items!!!
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:531)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:341)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:207)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:115)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:316)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:163)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:239)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:351)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:112)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
2019-05-14 22:36:56 [pool-2-thread-9] WARN  ParallelTaskRunner:761 - Catch InterruptedException 
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.getBatch(ParallelTaskRunner.java:791)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:758)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:727)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:418 - read:  timeReading                  = 409.276s
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:419 - read:  timeBlockedAtPutRead         = 134008.909s
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:420 - task;  timeBlockedAtTakeRead        = 0.000s(total)   ~0.000s/thread
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:424 - task;  timeTaskApply                = 0.000s(total)   ~0.000s/thread
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:428 - task;  timeBlockedAtPutWrite        = 0.000s(total)   ~0.000s/thread
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:430 - write: timeBlockedWatingDataToWrite = 130153.890s
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:431 - write: timeWriting                  = 4264.190s
2019-05-14 22:37:12 [main] INFO  ParallelTaskRunner:434 - total:                              = 134935.631s
2019-05-14 22:37:12 [main] ERROR VariantAnnotationStorageOperation:174 - Error annotating variants.
org.opencb.opencga.storage.core.variant.annotation.VariantAnnotatorException: Error creating annotations
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:209)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:115)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:316)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:163)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:239)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:351)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:112)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
Caused by: java.util.concurrent.ExecutionException: Error while running ParallelTaskRunner. Found 1 exceptions.
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:438)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:207)
	... 8 more
Caused by: java.util.concurrent.TimeoutException: Queue got stuck with 16 items!!!
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:531)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:341)
	... 10 more
org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error annotating variants.
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:176)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:239)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.annotate(VariantCommandExecutor.java:351)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:112)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
Caused by: org.opencb.opencga.storage.core.variant.annotation.VariantAnnotatorException: Error creating annotations
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:209)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:115)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:316)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:163)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: Error while running ParallelTaskRunner. Found 1 exceptions.
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:438)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:207)
	... 8 more
Caused by: java.util.concurrent.TimeoutException: Queue got stuck with 16 items!!!
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:531)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:341)
	... 10 more

**Comment by imedina** [comment]
Hi Mohammedhusen,

It seems you were executing the variant annotation right? This error occurs sometimes when CellBase is not available, can you copy the CellBase configuration in storage-configuration.yml file? Thanks and sorry for the issue.

**Comment by Mohammedhusen** [comment]
Hi imedina,

Thanks for your replay on this.

Here is the config file ..today also we faced the similar issue.

---
logLevel: "INFO"
logFile: null

openRegister: false
userDefaultQuota: 200000

databasePrefix: opencga
dataDir: /data/opencga/sessions
tempJobsDir: /data/opencga/sessions/jobs
toolDir: /opt/opencga/tools

admin:
  password: ""
  email: ""

audit:
  maxDocuments: 20000000 # Maximum number of documents that will be created in the audit collection.
  maxSize: 100000000000  # Maximum size that the audit collection will have in bytes.
  javaClass: ""          # Java class of the audit implementation to be used to audit.
  exclude: []            # Array of resource:action to select pairwise resource-actions to be excluded for audit purposes.

monitor:
  daysToRemove: 30
  executionDaemonInterval: 4000 # number of milliseconds between checks
  fileDaemonInterval: 8000      # number of milliseconds between checks
  port: 9092

execution:
  mode: LOCAL
  defaultQueue: ""
  availableQueues: ""
  toolsPerQueue: {}

email:
  host: 
  port: 
  user: 
  password: 
  from: ""
  ssl: false

#hooks:
#  user@project:study:              # Full Qualified Name of the study.
#    file:                          # Entity where the hook will be checked
#     - field: "name"               # Field of the entity to be checked
#       value: "~(.*)SV.vcf.gz$"    # Value that needs to be satisfied to perform the hook action
#       stage: "CREATE"             # Stage when the hook will be checked
#       action: "ADD"               # Action to be performed
#       where: "tags"               # Field over which the action will be performed
#       what: "SV"                  # Value to be updated

catalog:
  # offset: Starting point for the catalog internal ids. Use a big offset number (1000000 for instance) if you plan to use numerical ids
  #         for names or aliases of any entity.
  offset: 0
  database:
    hosts:
    - x.x.x.x.:27017
    user: 
    password: 
    options:
      authenticationDatabase: 
      connectionsPerHost: 20
  ## Solr configuration, by default is the same than storage
  search:
    # List of hosts pointing either to the Solr nodes directly using a complete URL or to the zookeper nodes with HOST:PORT
    #    Example for Solr connection:       http://opencga-solr-01.zone:8983/solr
    #    Example for Zookeeper connection:  opencga-zookeeper-01:2181               <-- Recommended for replicated installations
    hosts:
    - http://:8983/solr/
    mode: "cloud"
    user: ""
    password: ""
    timeout: 30000
    insertBatchSize: 2000

authentication:
  # Session expiration time in seconds
  expiration: 360000
# LDAP configuration example
  authenticationOrigins:
#  - id: ldap            # Any id
#    type: LDAP
#    host: ldap://localhost:9000
#    options:
#      usersSearch: dc=ge,dc=co,dc=uk # Base search to look for the users
#      groupsSearch: ou=general,ou=groups,dc=ge,dc=co,dc=uk # Base search to look for the groups
#  - id: aad                                               # Any id
#    type: AzureAD
#    host:
#    options:
#      tenantId: xxxx              # Mandatory. Tenant id
#      authClientId: xxxx          # Mandatory. Client id of the client with permissions to authenticate users.
#      syncClientId: xxxx          # Mandatory. Client id of the client with permissions to inspect active directory.
#      syncSecretKey: xxxx         # Mandatory: Secret key of the client with permissions to inspect active directory.
#      filters: tokenField1=aa,bb,cc;tokenField2=aa,bb,cc  # Optional. Filters to be applied. OpenCGA will check if tokenField1 = aa or bb
#                # or cc and tokenField2 = aa or bb or cc. If any of the filters don't succeed, even if the user is properly authenticated
#                # in AAD, the user will not be able to generate a token and login in OpenCGA.

server:
  rest:
    port: 9090
    logFile: null
    defaultLimit: 2000
    maxLimit: 5000

  grpc:
    port: 9091
    logFile: null
