### ISSUE TITLE
HashMap$Node cannot be cast to java.util.HashMap$TreeNode

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1323]
Hi Team,

Getting below error while loading the sample into opencga.

opencga version: 1.4.1

Need your quick help to solve this issue asap.

```
MongoDBVariantStoragePipeline:868 - About to load split data for samples in file ALL.chr12.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
2019-06-17 13:39:09 [main] INFO  MongoDBVariantStoragePipeline:340 - Multi thread direct load... [1 readerThreads, 6 tasks, 1 writerThreads]
2019-06-17 13:39:11 [pool-1-thread-4] ERROR MongoDBVariantMerger:407 - Error processing variant 12:83226:G:A
java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1827)
	at java.util.HashMap$TreeNode.treeify(HashMap.java:1944)
	at java.util.HashMap.treeifyBin(HashMap.java:771)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToSamplesConverter.getSampleId(DocumentToSamplesConverter.java:669)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToSamplesConverter.convertToStorageType(DocumentToSamplesConverter.java:473)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToStudyVariantEntryConverter.convertToStorageType(DocumentToStudyVariantEntryConverter.java:297)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToStudyVariantEntryConverter.convertToStorageType(DocumentToStudyVariantEntryConverter.java:258)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processVariant(MongoDBVariantMerger.java:521)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processVariants(MongoDBVariantMerger.java:404)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.merge(MongoDBVariantMerger.java:363)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.apply(MongoDBVariantMerger.java:291)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2019-06-17 13:39:11 [pool-1-thread-4] ERROR MongoDBVariantMerger:296 - Fail loading batch from 12:     83226:G:A to 12:     86561:A:G
2019-06-17 13:39:11 [pool-1-thread-4] ERROR ParallelTaskRunner:629 - Error processing batch 3
java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1827)
	at java.util.HashMap$TreeNode.treeify(HashMap.java:1944)
	at java.util.HashMap.treeifyBin(HashMap.java:771)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToSamplesConverter.getSampleId(DocumentToSamplesConverter.java:669)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToSamplesConverter.convertToStorageType(DocumentToSamplesConverter.java:473)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToStudyVariantEntryConverter.convertToStorageType(DocumentToStudyVariantEntryConverter.java:297)
	at org.opencb.opencga.storage.mongodb.variant.converters.DocumentToStudyVariantEntryConverter.convertToStorageType(DocumentToStudyVariantEntryConverter.java:258)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processVariant(MongoDBVariantMerger.java:521)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processVariants(MongoDBVariantMerger.java:404)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.merge(MongoDBVariantMerger.java:363)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.apply(MongoDBVariantMerger.java:291)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2019-06-17 13:39:11 [pool-1-thread-4] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-06-17 13:39:11 [main] WARN  ParallelTaskRunner:538 - Abort read thread on fail
```

**Comment by Mohammedhusen** [comment]
Hi Guys,

Any update on this issue?

**Comment by j-coll** [comment]
I'm after this now. Have you tried to load this file again?

**Comment by j-coll** [comment]
This error is due to a race condition that I had never seen before. I'm fixing it now.
Most likely, it will work if you try to load again the file.

**Comment by j-coll** [comment]
The issue should be solved now. Please, let me know if you still have issues. Otherwise, I'll close the ticket.

**Comment by Mohammedhusen** [comment]
Thanks for your quick support.

Rerunning the file solves the issue.

Just wanted to know under which build this issue you have fixed?

since we have loaded some data already, in that case, how can we deploy these new changes without affecting exiting stuff?
