### ISSUE TITLE
Missing Variant for update : '17:  72889677::GGCTCCGTAGGTTCCATGGGCTCCGTAGGTTCCATC'

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1411]

**Comment by Mohammedhusen** [comment]
Hi Team,

Getting below error while loading VCF file .Is there option ignore this error process with next loading.

2019-11-04 14:24:16 [pool-1-thread-7] ERROR MongoDBVariantMergeLoader:336 - Missing Variant '17:  72889677::GGCTCCGTAGGTTCCATGGGCTCCGTAGGTTCCATC'
2019-11-04 14:24:16 [pool-1-thread-7] ERROR ParallelTaskRunner:748 - Error writing batch 1217
java.lang.RuntimeException: Missing Variant for update : '17:  72889677::GGCTCCGTAGGTTCCATGGGCTCCGTAGGTTCCATC', 
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.onUpdateError(MongoDBVariantMergeLoader.java:339)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.updateStage(MongoDBVariantMergeLoader.java:203)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.executeMongoDBOperations(MongoDBVariantMergeLoader.java:159)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMergeLoader.write(MongoDBVariantMergeLoader.java:126)
	at org.opencb.opencga.storage.mongodb.variant.load.direct.MongoDBVariantDirectLoader.write(MongoDBVariantDirectLoader.java:85)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:746)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:729)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2019-11-04 14:24:16 [pool-1-thread-7] WARN  ParallelTaskRunner:754 - Abort writing thread on fail
2019-11-04 14:24:16 [pool-1-thread-1] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2019-11-04 14:24:16 [pool-1-thread-6] WARN  ParallelTaskRunner:641 - Abort task thread on fail
