### ISSUE TITLE
Inconsistent lock status Exception

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1462]
Under certain high-stress scenarios, we can see these exceptions coming from the VariantStorageMetadataManager. 

```
2020-01-09 12:25:07 [main] ERROR VariantFileIndexerOperationManager:279 - Error executing INDEX
org.opencb.opencga.storage.core.exceptions.StoragePipelineException: Exception executing load: Inconsistent lock status. You don't have the lock! Row: 'S_1', column: 'lock'. -768026962 != 298018841 from [CURRENT-EhlTvoUuqF:1578572716843]
	at org.opencb.opencga.storage.core.StorageEngine.loadFile(StorageEngine.java:134)
	at org.opencb.opencga.storage.core.StorageEngine.index(StorageEngine.java:105)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.index(VariantStorageEngine.java:254)
	at org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine.index(HadoopVariantStorageEngine.java:174)
	at org.opencb.opencga.analysis.variant.manager.operations.VariantFileIndexerOperationManager.indexFiles(VariantFileIndexerOperationManager.java:277)
	at org.opencb.opencga.analysis.variant.manager.operations.VariantFileIndexerOperationManager.index(VariantFileIndexerOperationManager.java:121)
	at org.opencb.opencga.analysis.variant.manager.VariantStorageManager.lambda$index$2(VariantStorageManager.java:176)
	at org.opencb.opencga.analysis.variant.manager.VariantStorageManager.secureOperation(VariantStorageManager.java:701)
	at org.opencb.opencga.analysis.variant.manager.VariantStorageManager.secureOperation(VariantStorageManager.java:666)
	at org.opencb.opencga.analysis.variant.manager.VariantStorageManager.index(VariantStorageManager.java:174)
	at org.opencb.opencga.analysis.variant.manager.VariantStorageManager.index(VariantStorageManager.java:169)
	at org.opencb.opencga.analysis.variant.operations.VariantIndexOperationTool.lambda$run$0(VariantIndexOperationTool.java:78)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.step(OpenCgaTool.java:369)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.step(OpenCgaTool.java:360)
	at org.opencb.opencga.analysis.variant.operations.VariantIndexOperationTool.run(VariantIndexOperationTool.java:76)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.start(OpenCgaTool.java:237)
	at org.opencb.opencga.analysis.tools.ToolRunner.execute(ToolRunner.java:81)
	at org.opencb.opencga.app.cli.internal.executors.VariantInternalCommandExecutor.index(VariantInternalCommandExecutor.java:356)
	at org.opencb.opencga.app.cli.internal.executors.VariantInternalCommandExecutor.execute(VariantInternalCommandExecutor.java:141)
	at org.opencb.opencga.app.cli.internal.InternalMain.privateMain(InternalMain.java:102)
	at org.opencb.opencga.app.cli.internal.InternalMain.main(InternalMain.java:32)
Caused by: org.opencb.opencga.storage.hadoop.utils.HBaseLock$IllegalLockStatusException: Inconsistent lock status. You don't have the lock! Row: 'S_1', column: 'lock'. -768026962 != 298018841 from [CURRENT-EhlTvoUuqF:1578572716843]
	at org.opencb.opencga.storage.hadoop.utils.HBaseLock.unlock(HBaseLock.java:189)
	at org.opencb.opencga.storage.hadoop.variant.metadata.AbstractHBaseDBAdaptor.unLock(AbstractHBaseDBAdaptor.java:244)
	at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseStudyMetadataDBAdaptor.unLockStudy(HBaseStudyMetadataDBAdaptor.java:107)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.unLockStudy(VariantStorageMetadataManager.java:164)
	at org.opencb.opencga.storage.core.metadata.VariantStorageMetadataManager.updateStudyMetadata(VariantStorageMetadataManager.java:198)
	at org.opencb.opencga.storage.core.variant.VariantStoragePipeline.preLoad(VariantStoragePipeline.java:409)
	at org.opencb.opencga.storage.hadoop.variant.HadoopVariantStoragePipeline.preLoad(HadoopVariantStoragePipeline.java:173)
	at org.opencb.opencga.storage.core.StorageEngine.loadFile(StorageEngine.java:122)
	... 20 more
```

These issues may produce inconsistencies in the metadata table.

**Comment by j-coll** [comment]
e0efe10c3f924a893758afd59fde9be394426799
