### ISSUE TITLE
Unable to calculate stats in opencga 2.0.0-RC1

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1637]
Hi Team,

While using opencga  2.0.0-RC1, we are getting the following error when running stats on the study , could you please help.

2020-08-10 10:05:48 [main] INFO  OpenCgaTool:363 - ------- Executing step 'prepare-cohorts' -------
2020-08-10 10:05:48 [main] INFO  OpenCgaTool:243 - ------- Tool 'variant-stats' executed in 0.628s [ 00:00:01 ] -------
org.opencb.opencga.core.exceptions.ToolException: Unable to compute variant stats for cohorts [ALL]
	at org.opencb.opencga.analysis.variant.stats.VariantStatsAnalysis.lambda$run$3(VariantStatsAnalysis.java:308)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.step(OpenCgaTool.java:364)
	at org.opencb.opencga.analysis.variant.stats.VariantStatsAnalysis.run(VariantStatsAnalysis.java:267)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.start(OpenCgaTool.java:229)
	at org.opencb.opencga.analysis.tools.ToolRunner.execute(ToolRunner.java:98)
	at org.opencb.opencga.app.cli.internal.executors.VariantInternalCommandExecutor.stats(VariantInternalCommandExecutor.java:431)
	at org.opencb.opencga.app.cli.internal.executors.VariantInternalCommandExecutor.execute(VariantInternalCommandExecutor.java:164)
	at org.opencb.opencga.app.cli.internal.InternalMain.privateMain(InternalMain.java:117)
	at org.opencb.opencga.app.cli.internal.InternalMain.main(InternalMain.java:32)

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

Could you please attach here the full log of the job, and the parameters of the job?

**Comment by Mohammedhusen** [comment]
Hi @j-coll ,

This is the only log I can see from the error log file.

cat variant-stats.20200810100544.a87Aod.err 
2020-08-10 10:05:48 [main] INFO  OpenCgaTool:362 - 
2020-08-10 10:05:48 [main] INFO  OpenCgaTool:363 - ------- Executing step 'prepare-cohorts' -------
2020-08-10 10:05:48 [main] INFO  OpenCgaTool:243 - ------- Tool 'variant-stats' executed in 0.628s [ 00:00:01 ] -------
org.opencb.opencga.core.exceptions.ToolException: Unable to compute variant stats for cohorts [ALL]
	at org.opencb.opencga.analysis.variant.stats.VariantStatsAnalysis.lambda$run$3(VariantStatsAnalysis.java:308)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.step(OpenCgaTool.java:364)
	at org.opencb.opencga.analysis.variant.stats.VariantStatsAnalysis.run(VariantStatsAnalysis.java:267)
	at org.opencb.opencga.analysis.tools.OpenCgaTool.start(OpenCgaTool.java:229)
	at org.opencb.opencga.analysis.tools.ToolRunner.execute(ToolRunner.java:98)
	at org.opencb.opencga.app.cli.internal.executors.VariantInternalCommandExecutor.stats(VariantInternalCommandExecutor.java:431)
	at org.opencb.opencga.app.cli.internal.executors.VariantInternalCommandExecutor.execute(VariantInternalCommandExecutor.java:164)
	at org.opencb.opencga.app.cli.internal.InternalMain.privateMain(InternalMain.java:117)
	at org.opencb.opencga.app.cli.internal.InternalMain.main(InternalMain.java:32)

**Comment by Mohammedhusen** [comment]
Hi @j-coll ,

Could you please update on this?

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

It seems that the cohort "ALL" is empty. Is this possible?
Could you copy here the output of these commands?

Full informaiton of the variant stats job:
```
opencga.sh jobs info --of json --job variant-stats.20200810100544.a87Aod --study <STUDY>
```

Full informaiton of the cohort ALL:
```
opencga.sh cohorts info --of json --cohort ALL --study <STUDY>
```
In case of not being able to share this information, as it might be sensitive data, please just check the number of samples within the cohort
