### ISSUE TITLE
Path collision at studies.alts remaining portion alts

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1660]
Hi Team,

We are getting below error while loading the VCF file using the opencga 1.4.1 version.

```
2020-10-08 13:17:09 [main] INFO  VariantFileIndexerStorageOperation:339 - 2 files found
2020-10-08 13:17:09 [main] WARN  VariantFileIndexerStorageOperation:448 - Job failed. Restoring status from LOADING to TRANSFORMED
2020-10-08 13:17:09 [main] INFO  CatalogStorageMetadataSynchronizer:122 - Synchronizing study testuser@grch37:test_study
org.opencb.opencga.storage.core.exceptions.StoragePipelineException: Exception executing load: Error executing direct load
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine.index(MongoDBVariantStorageEngine.java:445)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.index(VariantFileIndexerStorageOperation.java:278)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:183)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:174)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:307)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:116)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:102)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:35)
Caused by: org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error executing direct load
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStoragePipeline.directLoad(MongoDBVariantStoragePipeline.java:371)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine.index(MongoDBVariantStorageEngine.java:387)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: Error while running ParallelTaskRunner. Found 2 exceptions.
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:438)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStoragePipeline.directLoad(MongoDBVariantStoragePipeline.java:348)
	... 8 more
Caused by: com.mongodb.MongoQueryException: Query failed with error code 31249 and error message 'Path collision at studies.alts remaining portion alts' on server localhost:27017
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:722)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:711)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:471)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:415)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:711)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:83)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:144)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
	at org.opencb.commons.datastore.mongodb.MongoDBCollection.privateFind(MongoDBCollection.java:235)
	at org.opencb.commons.datastore.mongodb.MongoDBCollection.find(MongoDBCollection.java:205)
	at org.opencb.opencga.storage.mongodb.variant.adaptors.VariantMongoDBAdaptor.get(VariantMongoDBAdaptor.java:501)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.fetchVariant(MongoDBVariantMerger.java:1031)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.mergeOverlappedVariants(MongoDBVariantMerger.java:933)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processOverlappedVariants(MongoDBVariantMerger.java:649)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processOverlappedVariants(MongoDBVariantMerger.java:546)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processVariants(MongoDBVariantMerger.java:398)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.merge(MongoDBVariantMerger.java:363)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.apply(MongoDBVariantMerger.java:291)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
```

**Comment by j-coll** [comment]
Hi @Mohammedhusen 

That is a quite cryptic error message...  Which MongoDB version are you using?

**Comment by Mohammedhusen** [comment]
Hi @j-coll ,
Thanks for your response.
We were using the latest MongoDB 4.4.0 and once we downgraded it to 4.0.9 issues got solved.
