### ISSUE TITLE
Unable to execute storage operation

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1663]
Hi Team,

We are getting a strange error below could you please help.
The job creating a folder and then giving an error folder should be empty!

org.opencb.opencga.storage.core.exceptions.StorageEngineException: Unable to execute storage operation. Outdir '/opt/opencga/sessions/jobs/J_2513' must be empty!
	at org.opencb.opencga.storage.core.manager.variant.operations.StorageOperation.outdirMustBeEmpty(StorageOperation.java:91)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.index(VariantFileIndexerStorageOperation.java:116)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:183)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:174)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:307)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:116)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:102)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:35)

**Comment by Mohammedhusen** [comment]
Hi @j-coll ,

Could you please update on this error?

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

This is strange, indeed. Could you list the content of that directory, please? 
Are you using the "local" executor?
Are you running multiple instances of the opencga-master (opencga-admin.sh catalog daemon) ?

**Comment by Mohammedhusen** [comment]
Hi @j-coll ,

Thanks for your response.

Here is the content of the directory.

![Screen Shot 2020-10-22 at 9 55 28 AM](https://user-images.githubusercontent.com/42175932/96835933-f119c500-144c-11eb-855f-ba158d08a529.png)

This error we are getting when using SGE executor in the 1.4.1 version.

**Comment by j-coll** [comment]
Thanks! 
I think I know how to fix this.
Are you planning to upgrade to v2.0.0 ?

**Comment by Mohammedhusen** [comment]
@j-coll ,

Glad to know that you have a solution to this issue.
Regarding upgrade to v2.0.0 yes we are planing if there is a stable version for both openCGA and IVA available.
Do you guys have a stable version of V2? if yes please share the link.
