### ISSUE TITLE
Authentication times out when LDAP is enabled

### ISSUE THREAD

**Issue by mwhamgenomics** [opencb/opencga#1714]
I first saw this problem in OpenCGA 1.4.x on Tomcat, but have also noticed it in OpenCGA 2.0.0 in Docker. When I haven't signed in in a while, the login process hangs and eventually gives a timeout error. Restarting the REST API fixes it temporarily:

```
$ opencga.sh users login -u <user>
User password: 
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at org.opencb.opencga.client.rest.AbstractParentClient.callRest(AbstractParentClient.java:340)
	at org.opencb.opencga.client.rest.AbstractParentClient.callRest(AbstractParentClient.java:290)
	at org.opencb.opencga.client.rest.AbstractParentClient.execute(AbstractParentClient.java:255)
	at org.opencb.opencga.client.rest.AbstractParentClient.execute(AbstractParentClient.java:180)
	at org.opencb.opencga.client.rest.clients.UserClient.login(UserClient.java:80)
	at org.opencb.opencga.client.rest.OpenCGAClient.login(OpenCGAClient.java:164)
	at org.opencb.opencga.app.cli.main.executors.catalog.UserCommandExecutor.login(UserCommandExecutor.java:107)
	at org.opencb.opencga.app.cli.main.executors.catalog.UserCommandExecutor.execute(UserCommandExecutor.java:84)
	at org.opencb.opencga.app.cli.main.OpencgaMain.main(OpencgaMain.java:146)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 19 more
[opencga@opencga-igmmvr vcf]$ docker restart opencga-rest
opencga-rest
[opencga@opencga-igmmvr vcf]$ opencga.sh users login -u <user>
User password: 
You have been logged in correctly. This is your new token <token...>
```

When this happens, it affects authentication for both local users and imported LDAP users. I think last time, I traced it to a hanging LDAP server connection that then blocks any authentication attempts in other threads. Will see if I can reproduce it in Docker/Jetty.

**Comment by pfurio** [comment]
Thanks Murray, I will investigate what we can do so local users are not affected when the LDAP server is hung.

**Comment by pfurio** [comment]
Just added some default timeout values for LDAP (connection timeout 500ms and read timeout 1000ms). These values can be configured in the LDAP configuration section like shown below:
```
#  - id: ldaps                                              # Any id
#    type: LDAP
#    host: ldaps://localhost:636                            # or ldap://localhost:123
#    options:
#      authUserId: ""                                       # Auth user id and password if querying the LDAP system requires authentication. By default, empty.
#      authPassword: ""                                     # Auth user id and password if querying the LDAP system requires authentication. By default, empty.
#      usersSearch: dc=ge,dc=co,dc=uk                       # Mandatory field. Base search to look for users. By default, empty.
#      groupsSearch: ou=general,ou=groups,dc=ge,dc=co,dc=uk # Mandatory field. Base search to look for groups. By default, empty.
#      fullNameKey: displayname                             # Key to get the user's full name when importing users. By default, 'displayname'.
#      memberKey: member                                    # Key within groups to extract the user id. By default, 'member'.
#      dnKey: dn                                            # Key to get the user's DN or RDN unique identifier. By default, 'dn'.
#      dnFormat: "%s"                                       # Formatter to extract the user's DN if it is contained within a larger string. By default, '%s' to take the whole string.
#      uidKey: uid                                          # Key to get the user id to be used in OpenCGA. By default, 'uid'.
#      uidFormat: "%s"                                      # Formatter to extract the user id if the uid is contained within a larger string. By default, '%s' to take the whole string.
#      sslInvalidCertificatesAllowed: false                 # If using LDAPs with a custom certificate, set to true to accept any certificate. By default, false.
#      connectionTimeout: 500                               # Connection timeout value. Default: 500 ms
#      readTimeout: 1000                                    # Read timeout value. Default: 1000 ms
```
