### ISSUE TITLE
CLI: Login improvements

### ISSUE THREAD

**Issue by halender** [opencb/opencga#1884]
Some improvements:

### 1. Login help menu does not show --password as required

Login --password option is required. Autogenerated CLI check this properly but Login help menu does NOT show --password as an option. 

```
cafetero@swdev:~$ ./opencga-client-2.2.0-SNAPSHOT/bin/opencga.sh users login -u [USER] <<< TO_BE_CHANGED
ERROR: The following option is required: [-p | --password]

Usage:   opencga.sh users login [options]

Options:
            -h, --help		Print this help  [false]
                --host	STRING	Use this server host instead of the default one in the client configuration 
       -L, --log-level	STRING	One of the following: 'error', 'warn', 'info', 'debug', 'trace' [info] 
           --no-header		Not include headers in the output (not applicable to json output-format)
                               [false]
    --out-format, --OF	STRING	Output format. one of {JSON, JSON_PRETTY, TEXT, YAML}  [TEXT]
       --refresh-token	STRING	The body web service refreshToken parameter 
           *-u, --user	STRING	User id, this must be unique in OpenCGA 
```

### 2. Login does not let use "-u" option 
```
cafetero@swdev:~$ ./opencga-client-2.2.0-SNAPSHOT/bin/opencga.sh login -u NBR <<< TO_BE_CHANGED
ERROR: Failed to initialize OpenCGA CLI null
java.lang.NullPointerException
	at org.opencb.opencga.app.cli.main.utils.LoginUtils.forceLogin(LoginUtils.java:11)
	at org.opencb.opencga.app.cli.main.utils.LoginUtils.parseLoginCommand(LoginUtils.java:43)
	at org.opencb.opencga.app.cli.main.utils.CommandLineUtils.processShortCuts(CommandLineUtils.java:104)
	at org.opencb.opencga.app.cli.main.OpencgaMain.parseCliParams(OpencgaMain.java:155)
	at org.opencb.opencga.app.cli.main.OpencgaMain.executeCli(OpencgaMain.java:108)
	at org.opencb.opencga.app.cli.main.OpencgaMain.main(OpencgaMain.java:54)
```

### 3. Login only lets input the password interactively. Does not let redirect with ```<<<``` neither with ```echo```

**Comment by pamag** [comment]
## Reviewed
version: opencga-client-2.2.0-SNAPSHOT_testing2.tar.gz 

- [x] pasword as rediretion `<<<'`and `echo |` works!  
- [x] user with hyppen 
- [ ] user with `-u` still does not work 
![image](https://user-images.githubusercontent.com/167875/153325991-af5af39a-dfcd-4916-baf2-8de659f685b8.png)
