### ISSUE TITLE
ERROR VariantStorageManager:562 - Can't calculate stats.

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#219]
We are trying to index a file using the WS from opencga 0.6.0 (develop branch).  The indexing tool populates the DB with all the variants but fails calculating stats. 

The logs contain the following error

```log
015-09-17 12:58:13 INFO  AnalysisJobExecutor:305 - ==========================================
2015-09-17 12:58:13 INFO  AnalysisJobExecutor:306 - Executing job index(59)
2015-09-17 12:58:13 INFO  AnalysisJobExecutor:308 - ==========================================

2015-09-17 12:58:14 INFO  IndexVariantsCommandExecutor:168 - Extract variants 'file:/opt/opencga/sessions/users/demo/projects/38/39/small.vcf'
2015-09-17 12:58:14 INFO  IndexVariantsCommandExecutor:173 - PreTransform variants 'file:/opt/opencga/sessions/users/demo/projects/38/39/small.vcf'
2015-09-17 12:58:15 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "index.status" : "READY"} , { "_studyId" : 39.0}]}, project: {"index.status":"READY","include":["id","name"],"studyId":39,"exclude":[]}, dbTime: 1
2015-09-17 12:58:15 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "bioformat" : "VARIANT"} , { "bioformat" : "ALIGNMENT"}]} , { "_studyId" : 39.0}]}, project: {"bioformat":["VARIANT","ALIGNMENT"],"include":["id","name","sampleIds","attributes.variantSource.metadata.variantFileHeader"],"studyId":39,"exclude":[]}, dbTime: 3
2015-09-17 12:58:15 INFO  IndexVariantsCommandExecutor:175 - Transform variants 'file:/opt/opencga/sessions/users/demo/projects/38/39/small.vcf'
2015-09-17 12:58:15 INFO  VariantStorageManager:252 - Transforming variants...
2015-09-17 12:58:15 INFO  VariantStorageManager:315 - Multi thread transform...
2015-09-17 12:58:15 INFO  StringDataReader:57 - Plain input compress
2015-09-17 12:58:15 INFO  StringDataWriter:60 - Gzip output compress
2015-09-17 12:58:15 INFO  StringDataReader:112 - read lines = 1000
2015-09-17 12:58:15 INFO  StringDataWriter:118 - written lines = 1000
2015-09-17 12:58:15 INFO  StringDataWriter:60 - Gzip output compress
2015-09-17 12:58:15 INFO  StringDataWriter:60 - Gzip output compress
2015-09-17 12:58:15 INFO  StringDataWriter:60 - Gzip output compress
2015-09-17 12:58:15 INFO  StringDataWriter:60 - Gzip output compress
read:  timeReading                  = 0.009005868s
read:  timeBlockedAtPutRead         = 1.56728E-4s
task;  timeBlockedAtTakeRead        = 2.835151751975899E8s
task;  timeTaskApply                = 0.998336438s
task;  timeBlockedAtPutWrite        = 1.93882E-4s
write: timeBlockedWatingDataToWrite = 0.238958729s
write: timeWriting                  = 0.060275672s
2015-09-17 12:58:15 INFO  VariantStorageManager:325 - end - start = 0.331s
2015-09-17 12:58:15 INFO  VariantStorageManager:326 - Variants transformed!
2015-09-17 12:58:15 INFO  IndexVariantsCommandExecutor:177 - PostTransform variants 'file:/opt/opencga/sessions/jobs/I_Rt7iqHw1kM/small.vcf.variants.json.gz'
2015-09-17 12:58:15 INFO  IndexVariantsCommandExecutor:182 - PreLoad variants 'file:/opt/opencga/sessions/jobs/I_Rt7iqHw1kM/small.vcf.variants.json.gz'
2015-09-17 12:58:15 INFO  IndexVariantsCommandExecutor:184 - Load variants 'file:/opt/opencga/sessions/jobs/I_Rt7iqHw1kM/small.vcf.variants.json.gz'
2015-09-17 12:58:15 INFO  MongoDBVariantStorageManager:248 - Loading variants...
2015-09-17 12:58:15 [1mINFO  MongoDBVariantStorageManager:257 - Multi thread load... [1 readerThreads, 3 writerThreads]
2015-09-17 12:58:16 INFO  VariantDBWriter:171 - Num variants written 1000
read:  timeReading                  = 0.21232791s
read:  timeBlockedAtPutRead         = 2.51962E-4s
task;  timeBlockedAtTakeRead        = 3.6856973611368316E8s
task;  timeTaskApply                = 1.590203049s
2015-09-17 12:58:16 INFO  CatalogStudyConfigurationManager:222 - Updating StudyConfiguration 39
2015-09-17 12:58:16 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "_id" : 43.0} , { "_studyId" : 39.0}]}, project: {"id":[43],"studyId":39,"include":[],"exclude":[]}, dbTime: 3
2015-09-17 12:58:16 INFO  MongoDBVariantStorageManager:330 - end - start = 0.733s
2015-09-17 12:58:16 INFO  MongoDBVariantStorageManager:331 - Variants loaded!
2015-09-17 12:58:16 INFO  IndexVariantsCommandExecutor:186 - PostLoad variants 'file:/opt/opencga/sessions/jobs/I_Rt7iqHw1kM/small.vcf.variants.json.gz'
2015-09-17 12:58:16 INFO  CatalogStudyConfigurationManager:222 - Updating StudyConfiguration 39
2015-09-17 12:58:16 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "_id" : 43.0} , { "_id" : 54.0}]} , { "_studyId" : 39.0}]}, project: {"id":[43,54],"studyId":39,"include":[],"exclude":[]}, dbTime: 3
2015-09-17 12:58:16 ERROR VariantStorageManager:562 - Can't calculate stats.
java.io.IOException: Different samples in cohort ALL:48. Samples in the StudyConfiguratin: 0. Samples provided 8. Invalidate stats to continue.
	at org.opencb.opencga.storage.core.variant.stats.VariantStatisticsManager.checkAndUpdateStudyConfigurationCohorts(VariantStatisticsManager.java:496)
	at org.opencb.opencga.storage.core.variant.stats.VariantStatisticsManager.createStats(VariantStatisticsManager.java:220)
	at org.opencb.opencga.storage.core.variant.VariantStorageManager.postLoad(VariantStorageManager.java:559)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager.postLoad(MongoDBVariantStorageManager.java:338)
	at org.opencb.opencga.storage.app.cli.IndexVariantsCommandExecutor.execute(IndexVariantsCommandExecutor.java:187)
	at org.opencb.opencga.storage.app.StorageMain.Main(StorageMain.java:100)
	at org.opencb.opencga.storage.app.StorageMain.main(StorageMain.java:32)
java.io.IOException: Different samples in cohort ALL:48. Samples in the StudyConfiguratin: 0. Samples provided 8. Invalidate stats to continue.
	at org.opencb.opencga.storage.core.variant.stats.VariantStatisticsManager.checkAndUpdateStudyConfigurationCohorts(VariantStatisticsManager.java:496)
	at org.opencb.opencga.storage.core.variant.stats.VariantStatisticsManager.createStats(VariantStatisticsManager.java:220)
	at org.opencb.opencga.storage.core.variant.VariantStorageManager.postLoad(VariantStorageManager.java:559)
	at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager.postLoad(MongoDBVariantStorageManager.java:338)
	at org.opencb.opencga.storage.app.cli.IndexVariantsCommandExecutor.execute(IndexVariantsCommandExecutor.java:187)
	at org.opencb.opencga.storage.app.StorageMain.Main(StorageMain.java:100)
	at org.opencb.opencga.storage.app.StorageMain.main(StorageMain.java:32)

2015-09-17 12:58:17 INFO  AnalysisJobExecutor:316 - ==========================================
2015-09-17 12:58:17 INFO  AnalysisJobExecutor:317 - Finished job index(59)
2015-09-17 12:58:17 INFO  AnalysisJobExecutor:318 - ==========================================
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "path" : "small.vcf.variants.json.gz"} , { "_studyId" : 39.0}]}, project: , dbTime: 0
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "small.vcf.variants.json.gz/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  CatalogFileUtils:134 - Moving file file:///opt/opencga/sessions/jobs/I_Rt7iqHw1kM/small.vcf.variants.json.gz -> file:/opt/opencga/sessions/users/demo/projects/38/39/small.vcf.variants.json.gz
2015-09-17 12:58:17 INFO  CatalogFileUtils:178 - Checksum not computed.
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 60}
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "small.vcf.variants.json.gz/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 60}
2015-09-17 12:58:17 INFO  FileScanner:255 - Added file small.vcf.variants.json.gz
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "path" : "index.59.out.txt"} , { "_studyId" : 39.0}]}, project: , dbTime: 0
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "index.59.out.txt/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  CatalogFileUtils:134 - Moving file file:///opt/opencga/sessions/jobs/I_Rt7iqHw1kM/index.59.out.txt -> file:/opt/opencga/sessions/users/demo/projects/38/39/index.59.out.txt
2015-09-17 12:58:17 INFO  CatalogFileUtils:178 - Checksum not computed.
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 61}
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "index.59.out.txt/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 1
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 61}
2015-09-17 12:58:17 INFO  FileScanner:255 - Added file index.59.out.txt
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "path" : "index.59.err.txt"} , { "_studyId" : 39.0}]}, project: , dbTime: 0
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "index.59.err.txt/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  CatalogFileUtils:134 - Moving file file:///opt/opencga/sessions/jobs/I_Rt7iqHw1kM/index.59.err.txt -> file:/opt/opencga/sessions/users/demo/projects/38/39/index.59.err.txt
2015-09-17 12:58:17 INFO  CatalogFileUtils:178 - Checksum not computed.
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 62}
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "index.59.err.txt/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 62}
2015-09-17 12:58:17 INFO  FileScanner:255 - Added file index.59.err.txt
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "path" : "small.vcf.file.json.gz"} , { "_studyId" : 39.0}]}, project: , dbTime: 0
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "small.vcf.file.json.gz/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  CatalogFileUtils:134 - Moving file file:///opt/opencga/sessions/jobs/I_Rt7iqHw1kM/small.vcf.file.json.gz -> file:/opt/opencga/sessions/users/demo/projects/38/39/small.vcf.file.json.gz
2015-09-17 12:58:17 INFO  CatalogFileUtils:178 - Checksum not computed.
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 63}
2015-09-17 12:58:17 [1mINFO  CatalogMongoDBAdaptor:624 - File search: query : { "$and" : [ { "$or" : [ { "path" : ""} , { "path" : "small.vcf.file.json.gz/"}]} , { "_studyId" : 39.0}]}, project: {"include":["uri","path"],"exclude":[]}, dbTime: 0
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 63}
2015-09-17 12:58:17 INFO  FileScanner:255 - Added file small.vcf.file.json.gz
2015-09-17 12:58:17 INFO  FileManager:455 - UserAdmin admin modifies file {id: 54}
```

**Comment by j-coll** [comment]
Thanks for reporting that. There was a problem while updating the cohort ALL, which contains all indexed samples.
