### ISSUE TITLE
Null pointer error for second file

### ISSUE THREAD

**Issue by abhi-mshetti** [opencb/opencga#348]
For a new study in a new project I can upload a vcf file and have it index. This works fine. When I try to upload a second file it throws a NPE.

Branch: Master

```
java.lang.NullPointerException
    at java.util.LinkedList.addAll(LinkedList.java:408)
    at java.util.LinkedList.addAll(LinkedList.java:387)
    at org.opencb.opencga.storage.mongodb.variant.VariantMongoDBAdaptor.getLoadedSamples(VariantMongoDBAdaptor.java:2102)
    at org.opencb.opencga.storage.mongodb.variant.VariantMongoDBWriter.pre(VariantMongoDBWriter.java:145)
    at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager$1TaskWriter.pre(MongoDBVariantStorageManager.java:277)
    at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:183)
    at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager.load(MongoDBVariantStorageManager.java:310)
    at org.opencb.opencga.storage.app.cli.IndexVariantsCommandExecutor.execute(IndexVariantsCommandExecutor.java:184)
    at org.opencb.opencga.storage.app.StorageMain.Main(StorageMain.java:100)
    at org.opencb.opencga.storage.app.StorageMain.main(StorageMain.java:32)
```

**Comment by j-coll** [comment]
I am trying to reproduce the error.
Can you provide more details about the exact steps you did?
Which kind of VCF files are you loading? Single sample or multi sample> Full genome or by chromosome?

**Comment by imedina** [comment]
Two more versions have been released and we could not reproduce it, please re-open it if you still have this problem
