### ISSUE TITLE
Avoid ScannerTimeoutException in MR

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#352]
After loading and merging 600-800 samples in HBase, the MapReduce job starts failing due to ScannerTimeoutExceptions:

```
org.apache.hadoop.hbase.client.ScannerTimeoutException: 88966ms passed since the last invocation, timeout i
s currently set to 60000
        at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:434)
        at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:364)
        at org.apache.hadoop.hbase.mapreduce.TableRecordReaderImpl.nextKeyValue(TableRecordReaderImpl.java:205)
        at org.apache.hadoop.hbase.mapreduce.TableRecordReader.nextKeyValue(TableRecordReader.java:147)
        at org.apache.hadoop.hbase.mapreduce.TableInputFormatBase$1.nextKeyValue(TableInputFormatBase.java:216)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:556)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: org.apache.hadoop.hbase.UnknownScannerException: org.apache.hadoop.hbase.UnknownScannerException: Name: 1214, already closed?
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:2226)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:32205)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2114)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:101)
        at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
        at java.lang.Thread.run(Thread.java:745)

```

Need to discover what's going on and how to avoid this exceptions.

**Comment by j-coll** [comment]
The `ScannerTimeoutException` is produced by a `UnknownScannerException`
This `UnknownScannerException` is thrown by the server when the `RegionScanner` (iterator on the server over the table) is not found.
A `RegionScanner` is automatically closed/removed from the server if has been idle for a `hbase.client.scanner.timeout.period`, which is 60s by default.

Up to this point, increasing the timeout to 120s avoids any exception.
(see https://hbase.apache.org/book.html#trouble.client.scantimeout)

The question now is... How is possible that a scanner was more than 60s idle, if processing each row takes less than a 5ms? (is really fast because I am only coping the `_V` column from the first to the second table)

The `ClientScanner` (which is the class that connects to the `RegionScanner` via gRPC) has a Scan Cache. Maybe, if this cache is really really big, we can be using the results from the cache for more than the timeout period. That will require a cache size of 12000 elements. Cache size is 50, so this is not the problem.
(see https://hbase.apache.org/book.html#perf.hbase.client.caching)

Reading the logs, you can see that there are some rows that take more than expected:

>     2016-08-23 15:49:44,954 INFO [attempt_1470327665103_0156_m_000071_0] org.opencb.opencga.storage.hadoop.variant.index.VariantTableMapper: Start mapping key: 8_000000017426
>     2016-08-23 15:49:44,956 INFO [attempt_1470327665103_0156_m_000071_0] org.opencb.opencga.storage.hadoop.variant.index.VariantTableMapper: Finished mapping key: 8_000000017426
>     2016-08-23 15:49:44,973 INFO [attempt_1470327665103_0156_m_000071_0] org.opencb.opencga.storage.hadoop.variant.index.VariantTableMapper: Start mapping key: 8_000000017427
>     2016-08-23 15:50:15,537 INFO [attempt_1470327665103_0156_m_000071_0] org.opencb.opencga.storage.hadoop.variant.index.VariantTableMapper: Finished mapping key: 8_000000017427


After adding some more logs, I realized that the operation "context.write()", sometimes, takes more than expected, from few seconds up to 90 seconds.
This is surprising, because the write operations are supposed to be asynchronous. The `TableOutputFormat` creates a `TableRecordWriter` to each Mapper. The `TableRecordWriter` uses a `BufferedMutator` to execute the puts and deletes in batches. The size of this buffer is really big, by default 2M mutations. This maybe explains why some write operations take so long. The buffer is full and needs to be flushed. But it's supposed to be async..

After decreasing the size of the buffer from 2M to 500k the timeouts where still there. Makes sense because the `BufferedMutator` is async.... as long as there are no errors..

The AsyncProcess is prepared to fail. And it fails!

>     A few failures is fine: region moved, then is not opened, then is overloaded.


The `BufferedMutator` has a max number of retries (35 by default), and, to give some time to the server to recover from whatever was happening, between every retry it sleeps the thread for a while.
Because this is very frequent, the fails are not logged until the 10th retry.

>     #6, table=opencga:bridge_4k_44, attempt=10/35 failed=45ops, last exception: null on hdp-node1.xcat.cluster,16020,1470327701812, tracking started null, retrying after=10075ms, replay=45ops
>     #6, table=opencga:bridge_4k_44, attempt=11/35 failed=45ops, last exception: null on hdp-node1.xcat.cluster,16020,1470327701812, tracking started null, retrying after=10088ms, replay=45ops
>     #6, table=opencga:bridge_4k_44, attempt=12/35 failed=45ops, last exception: null on hdp-node1.xcat.cluster,16020,1470327701812, tracking started null, retrying after=20070ms, replay=45ops
>     #6, table=opencga:bridge_4k_44, attempt=13/35 succeeded on hdp-node1.xcat.cluster,16020,1470327701812, tracking started Tue Aug 23 15:48:17 BST 2016


The time that the `AsyncProcess` sleeps increases each attempt: 100ms, 200ms, 300ms, 500ms, 1s, 2s, 4s, 10s, 10s, 20s
This sleeps are done in the mapper "main" thread, causing that the `RegionScanner` is clean up from the server.

Increasing the `hbase.client.scanner.timeout.period` will increase the life of the `RegionScanner` in the server, so it won't disappear.
The delays produced by the `BufferedMutator` are within normal and I haven't seen any possible cause for the errors to worry about.
