### ISSUE TITLE
Getting started in 5 minutes: User login error  

### ISSUE THREAD

**Issue by AlfredoIacoangeli** [opencb/opencga#413]
Hello everybody! 
I was trying to install and try opencga.
I downloaded the latest stable version: 1.0.0-rc1
Installed it following the instructions and now I am trying the tutorial Getting started in 5 minutes.

After creating the database and the user "alfredo" I tried to log in as the user:
./bin/opencga.sh users login -u alfredo -p
it askes me for the password and then print the following error and waring message:

2016-10-20 10:05:45 [main] WARN  UsersCommandExecutor:101 - No Session file
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused
    at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
    at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
    at org.opencb.opencga.client.rest.AbstractParentClient.callRest(AbstractParentClient.java:298)
    at org.opencb.opencga.client.rest.AbstractParentClient.execute(AbstractParentClient.java:216)
    at org.opencb.opencga.client.rest.AbstractParentClient.execute(AbstractParentClient.java:155)
    at org.opencb.opencga.client.rest.UserClient.login(UserClient.java:97)
    at org.opencb.opencga.client.rest.OpenCGAClient.login(OpenCGAClient.java:128)
    at org.opencb.opencga.app.cli.main.executors.catalog.UsersCommandExecutor.login(UsersCommandExecutor.java:181)
    at org.opencb.opencga.app.cli.main.executors.catalog.UsersCommandExecutor.execute(UsersCommandExecutor.java:80)
    at org.opencb.opencga.app.cli.main.OpencgaMain.main(OpencgaMain.java:117)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
    at org.glassfish.jersey.client.internal.HttpUrlConnector$4.getOutputStream(HttpUrlConnector.java:385)
    at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:200)
    at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:194)
    at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:228)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    at org.glassfish.jersey.message.internal.ReaderWriter.writeToAsString(ReaderWriter.java:193)
    at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeToAsString(AbstractMessageReaderWriterProvider.java:130)
    at org.glassfish.jersey.message.internal.StringMessageProvider.writeTo(StringMessageProvider.java:99)
    at org.glassfish.jersey.message.internal.StringMessageProvider.writeTo(StringMessageProvider.java:59)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
    at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
    at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:517)
    at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:499)
    at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:388)
    at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
    ... 17 more

Can anybody help me? I am not expert in java.

Thanks a lot in advance

Alfredo

**Comment by pfurio** [comment]
According to the kind of error you are getting, it seems that the client could not get in touch with the webservices. Do you have them running?

You should follow this guide first: https://github.com/opencb/opencga/wiki/Download-and-Installation
Once you have the database and the webservices running, you can then follow the Getting started in 5 minutes.

If that was not the case, it could be that the configuration file is not pointing to the host where the webservices are running. You should change this line https://github.com/opencb/opencga/blob/develop/opencga-client/src/main/resources/client-configuration.yml#L7 to something like the code below if you have it running in localhost. 

`rest:
  host: "http://localhost:8080/opencga/"
`

Please let us know if any of this solved your problem or you are still struggling with it.

**Comment by melsiddieg** [comment]
Hi Pedro

I have the same problem unable to login since the last update, My conf file
seems to be fine and is pointing to the correct rest host

**Comment by pfurio** [comment]
Hi, I would be happy to help but I tried different things and I am unable to get the same errors you are having. If I start everything from scratch (new installation on a new database), everything works fine for me. Could any of you be more specific regarding the steps you take from the very beginning? Let's say, compilation, new mongoDB, tomcat deployment... Do you have tomcat and mongoDB in separate servers? Can you see the swagger documentation?

Apologies for the inconveniences.
