### ISSUE TITLE
CatalogException: Unable to modify a cohort while it's in status "CALCULATING"

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#463]
v1.0.0-**rc2.1** fails to calculate stats w/ below exception while loading VCF, v1.0.0-**rc1** has no issue like that. MongoDB in both cases.

```
org.opencb.opencga.storage.core.exceptions.StorageManagerException: Different samples in cohort ALL:1179. Samples in the StudyConfiguration: 0. Samples provided 1169. Invalidate stats to continue.
        at org.opencb.opencga.storage.core.variant.stats.VariantStatisticsManager.checkAndUpdateStudyConfigurationCohorts(VariantStatisticsManager.java:509)
        at org.opencb.opencga.storage.core.variant.stats.VariantStatisticsManager.createStats(VariantStatisticsManager.java:154)
        at org.opencb.opencga.storage.core.variant.VariantStorageETL.postLoad(VariantStorageETL.java:846)
        at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageETL.postLoad(MongoDBVariantStorageETL.java:659)
        at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager.index(MongoDBVariantStorageManager.java:201)
        at org.opencb.opencga.analysis.variant.VariantFileIndexer.index(VariantFileIndexer.java:272)
        at org.opencb.opencga.analysis.variant.VariantFileIndexer.index(VariantFileIndexer.java:97)
        at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.index(VariantCommandExecutor.java:356)
        at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.execute(VariantCommandExecutor.java:115)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:92)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:31)
org.opencb.opencga.catalog.exceptions.CatalogException: Unable to modify a cohort while it's in status "CALCULATING"
        at org.opencb.opencga.catalog.managers.CohortManager.update(CohortManager.java:194)
        at org.opencb.opencga.catalog.managers.CohortManager.update(CohortManager.java:53)
        at org.opencb.opencga.analysis.variant.VariantFileIndexer.updateDefaultCohorts(VariantFileIndexer.java:569)
        at org.opencb.opencga.analysis.variant.VariantFileIndexer.updateFileInfo(VariantFileIndexer.java:448)
        at org.opencb.opencga.analysis.variant.VariantFileIndexer.index(VariantFileIndexer.java:296)
        at org.opencb.opencga.analysis.variant.VariantFileIndexer.index(VariantFileIndexer.java:97)
        at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.index(VariantCommandExecutor.java:356)
        at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.execute(VariantCommandExecutor.java:115)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:92)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:31)
```

**Comment by j-coll** [comment]
Hi @dnafault,

It seems that a calculate-stats operation failed and it is in an wrong "CALCULATING" status. This is a common issue, when the operation ends abruptly and can't recover.

This is a known issue that may happen also for index operations. To fix this, we have 2 solutions:

1. Add a param --resume for continue this operations
2. A way of detect automatically if the previous operation has dead and it needs to be resumed.

The resume parameter exists internally, but not in the CLI. Despite we are working on the second point (where resuming manually is not needed) is interesting to have this param.

**Comment by j-coll** [comment]
The patch will be added to the next release.

To solve this issue in v1.0.0-rc2.1, you can invalidate all the pending cohorts by executing this command in the catalog database:
```javascript
db.cohort.update({"status.name":"CALCULATING"},{$set:{"status.name":"INVALID"}},{multi:true})
```

**Comment by dnafault** [comment]
Thanks Jacobo, it's more interesting why it failed in the first place and what happens if it fails every time opencga automatically resumes the operation.

**Comment by j-coll** [comment]
If you send me the stack trace or the log file of the execution, I can try to discover why did it fail.

Another thing that needs to me implemented is the roll-back. Is very unlikely that a file was transformed correctly can not be loaded, but definitely not impossible. Rolling back the database will remove all the non finished files and will set to invalid all the non finished statistics. 

Please, feel free to close this issue whenever is fine for you.

**Comment by dnafault** [comment]
I'll look at stack traces next time this happens. I had to finish loading asap so was happy to do this with v1.0.0-rc1. The error was persistent with v1.0.0-rc2.1.
