### ISSUE TITLE
"Timeout" error when filtering variants by FILES

### ISSUE THREAD

**Issue by danielnavarrogomez** [opencb/opencga#493]
Hi Guys,

I pulled fresh code less than an hour ago.

I found a bug when using REST asking for a query with GET parameters that is not happening when you use POST:

Let's say that the query that I'm doing has 2800 variants, using this get URL I ask for the first 2000 variants:

`http://opencga.meei.harvard.edu/opencga/webservices/rest/v1/analysis/variant/query?sid=nhMS3dD82XKDtkSxdgOB&returnedSamples=022-072&studies=2&files=7&skip=0&limit=2000&genotype=022-072%3A0%2F1%2C1%2F1`

This one works fine, so now I need to ask for the rest of the variants skipping the first 2000:

`http://opencga.meei.harvard.edu/opencga/webservices/rest/v1/analysis/variant/query?sid=nhMS3dD82XKDtkSxdgOB&returnedSamples=022-072&studies=2&files=7&skip=2000&limit=2000&genotype=022-072%3A0%2F1%2C1%2F1`

This one gives me a "timeout" error:
`{"apiVersion":"v1","warning":"","error":"operation exceeded time limit","queryOptions":{"metadata":true,"skip":5500,"limit":500},"response":[{"id":"","time":0,"dbTime":-1,"numResults":-1,"numTotalResults":-1,"warningMsg":"Future errors will ONLY be shown in the QueryResponse body","errorMsg":"DEPRECATED: com.mongodb.MongoExecutionTimeoutException: operation exceeded time limit","resultType":"","result":[]}]}`

Checking tomcat log the error is different:
```
Request GET
2017-01-11 12:31:14 [http-nio-8080-exec-31] INFO  OpenCGAWSServer:387 - URL: http://localhost:8080/opencga/webservices/rest/v1/analysis/variant/query, query = {"studies":"2","files":"7","returnedSamples":"022-072","genotype":"022-072:0/1,1/1"}, queryOptions = {"metadata":true,"skip":2000,"limit":2000}
11-Jan-2017 12:31:14.404 SEVERE [http-nio-8080-exec-33] org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse An I/O error has occurred while writing a response message entity to the container output stream.
 org.glassfish.jersey.server.internal.process.MappableException: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
[...]
```

**Comment by j-coll** [comment]
After debugging a while, this problem has to be with the used indexes and the type of data (a lot of small files)

**Comment by j-coll** [comment]
Please, open again if the error persists.
