### ISSUE TITLE
java.net.URISyntaxException for hostnames with ':'

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#498]
1.0.0-rc3

While parsing a hostname from storage-configuration.yml, it fails with exception below if ':' is presented in hostname

```
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 111.111.111.111:60000
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.checkChar(URI.java:3031)
	at java.net.URI$Parser.parse(URI.java:3047)
	at java.net.URI.<init>(URI.java:588)
	at org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine.buildCredentials(HadoopVariantStorageEngine.java:488)
```

**Comment by j-coll** [comment]
As an intermediate solution, writing `hbase://111.111.111.111:60000` or just the IP `111.111.111.111` instead of `111.111.111.111:60000` works.

Also, if the command `hbase` is available in that computer, the hadoop configuracion will be read from the filesystem (by adding the configuration folders to the classpath. see [opencga-env.sh](https://github.com/opencb/opencga/blob/develop/opencga-app/app/bin/opencga-env.sh)). In that case, just leave that field empty.
