### ISSUE TITLE
Error merging overlapped SV variants in MongoDB

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#504]
This error happens after loading the third file from a batch of files.

```
2017-01-18 10:02:06 [pool-3-thread-6] ERROR MongoDBVariantMerger:446 - Error processing variant 2:1735055:CTTCCTGGACATGCAGCTGACCTCCGCATCCCAGCACCCTTGCATCTGGG:- in overlapped variants [2:1735055:CTTCCTGGACATGCAGCTGACCTCCGCATCCCAGCACCCTTGCATCTGGG:-, 2:1735066:T:C, 2:1735066:T:G]
2017-01-18 10:02:06 [pool-3-thread-6] ERROR MongoDBVariantMerger:267 - Fail loading batch from  2:   1709776:G:C to  2:   1761374:G:T
2017-01-18 10:02:06 [pool-3-thread-6] ERROR ParallelTaskRunner:582 - Error processing batch 2418
java.lang.NullPointerException
	at org.opencb.biodata.tools.variant.merge.VariantMerger.lambda$updateGT$12(VariantMerger.java:472)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.opencb.biodata.tools.variant.merge.VariantMerger.updateGT(VariantMerger.java:472)
	at org.opencb.biodata.tools.variant.merge.VariantMerger.lambda$null$7(VariantMerger.java:374)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.opencb.biodata.tools.variant.merge.VariantMerger.lambda$mergeVariants$8(VariantMerger.java:358)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.opencb.biodata.tools.variant.merge.VariantMerger.mergeVariants(VariantMerger.java:344)
	at org.opencb.biodata.tools.variant.merge.VariantMerger.merge(VariantMerger.java:219)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.mergeOverlappedVariants(MongoDBVariantMerger.java:792)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processOverlappedVariants(MongoDBVariantMerger.java:467)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.processOverlappedVariants(MongoDBVariantMerger.java:440)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.merge(MongoDBVariantMerger.java:311)
	at org.opencb.opencga.storage.mongodb.variant.load.variants.MongoDBVariantMerger.apply(MongoDBVariantMerger.java:262)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:580)
	at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:547)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-01-18 10:02:06 [pool-3-thread-6] WARN  ParallelTaskRunner:594 - Abort task thread on fail
2017-01-18 10:02:06 [pool-3-thread-7] WARN  ParallelTaskRunner:698 - Abort writing thread on fail
```

**Comment by j-coll** [comment]
After debugging a while, I have seen that the database, after loading the second file, contains in the list of secondary alternates the main variant:

``` json
{
  "_id" : " 1:   1735056:CTTCTCTTTTTTTTTTTTTTTTTTTGGGCTTCTCTTTTTTTTTTTTTTTT:",
  "chromosome" : "1",
  "start" : 1735056,
  "end" : 1735105,
  "length" : 50,
  "reference" : "CTTCTCTTTTTTTTTTTTTTTTTTTGGGCTTCTCTTTTTTTTTTTTTTTT",
  "alternate" : "",
  "type" : "SV",
  "studies" : [
    {
      "sid" : 1,
      "files" : [
        {
          "fid" : 0,
          "_ori" : {
            "s" : "1735055:ACTTCTCTTTTTTTTTTTTTTTTTTTGGGCTTCTCTTTTTTTTTTTTTTTT:A",
            "i" : 0
          }
        },
        {
          "fid" : 1,
          "_ori" : {
            "s" : "1735066:T:C",
            "i" : 0
          }
        }
      ],
      "alts" : [
        {
          "chr" : "1",
          "ref" : "T",
          "alt" : "C",
          "start" : 1735066,
          "end" : 1735066,
          "type" : "SNV"
        },
        {
          "chr" : "1",
          "ref" : "CTTCTCTTTTTTTTTTTTTTTTTTTGGGCTTCTCTTTTTTTTTTTTTTTT",
          "alt" : "",
          "start" : 1735056,
          "end" : 1735105,
          "type" : "SV"
        }
      ]
    }
  ]
}
```

Which causes the NPE in the variant merger when appears a new variant overlapping with that region.

How it's possible to have that duplicated secondary alternate? We can see here that the variant has length 50 and type SV, as the alternate. But if we see the `inferType` method in Variant.java, we see that a variant is SV if is strictly greater than 50, so this variant should be an INDEL instead of a SV.

Reading the `_ori` field, we see that the variant, originally, had one extra base in the reference, removed in the Normalize process. In that process, **the variant type should have changed from SV to INDEL**. 

The MongoDBVariantMerger creates new empty variants before calling to the VariantMerger. For the new variant, the type is INDEL instead of SV. Merging the original SV on top of that variant, creates the extra secondary alternate.

**Comment by j-coll** [comment]
The issue has been fixed in biodata.
An affected database can be repaired using the following script:
https://gist.github.com/j-coll/cb523ba937a9efb47f9a4f4acd23f82f
