### ISSUE TITLE
Hadoop storageEngine in rc3

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#510]
In Release Notes for v1.0.0-rc3 it says:

> **Known Issues**
> 
> 	OpenCGA storage hadoop is not available in this version. To compile use this line:
> 
> 	`mvn clean install -DskipTests -pl '!:opencga-storage-hadoop-core'`
>

Can you please provide more details about what part is affected/non-functional ? We tested Hadoop storageEngine with rc3 and loaded the first gvcf files to HBase via rc3, but REST API is failing and concurrent loading is failing as well.

**Comment by j-coll** [comment]
OpenCGA storage hadoop has not been fully tested and validated, and it should not be used in production yet. Changes may happen, forcing data to be loaded again. There is still room for improvement in some aspects of query performance. And we have to define and complete a set of configuration parameters.

We have now some analysts validating the correctness of the loaded data.

I have answered about the concurrent loading in #511.
In any case, the REST API should not fail. Could you provide more details about this?

**Comment by dnafault** [comment]
Thanks, that's understandable. We just started to test opencga with HBase. Not much in log files, that's all we have in Tomcat's logs:

```
129.94.15.158 - - [31/Jan/2017:06:55:20 +0000] "GET /opencga-1.0.0-rc3/webservices/rest/v1/studies/2/variants?sid=pdzTSJCB8e4L5ovaZSte&chromosome=1&histogram=false&interval=2000&merge=false&limit=1 HTTP/1.1" 500 383
```


and here is a response:

```
{
  "apiVersion": "v1",
  "warning": "",
  "error": "java.lang.NullPointerException",
  "queryOptions": {
    "metadata": true,
    "limit": 1
  },
  "response": [
    {
      "id": "",
      "time": 0,
      "dbTime": -1,
      "numResults": -1,
      "numTotalResults": -1,
      "warningMsg": "Future errors will ONLY be shown in the QueryResponse body",
      "errorMsg": "DEPRECATED: java.lang.RuntimeException: java.lang.NullPointerException",
      "resultType": "",
      "result": []
    }
  ]
}
```

**Comment by j-coll** [comment]
There should be in the `catalina.out` an stack trace with the complete error. If not, it should be in the `server.log`.

Without more information, I can not know what's going on.

**Comment by dnafault** [comment]
OpencCGA silently just doesn't create server.log if a directory where it wants to create it doesn't exist.  

Original stack trace for NPE is below. It's a bit odd it comes from HBase code (ZooKeeperWatcher.getMetaReplicaNodes).

We have zookeeper.znode.parent = "/hbase-unsecure" in /etc/hbase/conf/hbase-site.xml, as expected for HDP. In the latest debug line before NPE there is "request:: '/hbase,F" - I'm not sure whether this means value for zookeeper.znode.parent, in which case NPE would be expected [1]

Exception comes only when REST API is called, we were able to load gVCFs from command line w/o exceptions. 

[1] https://groups.google.com/forum/#!topic/nosql-databases/FNKGaBtLrro

```
2017-02-23 04:46:00 [http-bio-8080-exec-9-SendThread(192.168.1.105:2181)] DEBUG ClientCnxn:818 - Reading reply sessionid:0x15a693e1d530005, packet:: clientPath:null serverPath:null finished:false hea
der:: 2,8  replyHeader:: 2,85899346945,-101  request:: '/hbase,F  response:: v{} 
2017-02-23 04:46:00 [http-bio-8080-exec-9] ERROR OpenCGAWSServer:430 - Catch error: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:208)
        at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:326)
        at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:301)
        at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:166)
        at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:161)
        at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:794)
        at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602)
        at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366)
        at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:405)
        at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseStudyConfigurationManager.lambda$getStudies$3(HBaseStudyConfigurationManager.java:182)
        at org.opencb.opencga.storage.hadoop.utils.HBaseManager.act(HBaseManager.java:276)
        at org.opencb.opencga.storage.hadoop.utils.HBaseManager.act(HBaseManager.java:260)
        at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseStudyConfigurationManager.getStudies(HBaseStudyConfigurationManager.java:182)
        at org.opencb.opencga.storage.hadoop.variant.metadata.HBaseStudyConfigurationManager.getStudies(HBaseStudyConfigurationManager.java:47)
        at org.opencb.opencga.storage.core.variant.adaptors.VariantDBAdaptorUtils.getStudyIds(VariantDBAdaptorUtils.java:180)
        at org.opencb.opencga.storage.core.variant.adaptors.VariantDBAdaptorUtils.getReturnedStudies(VariantDBAdaptorUtils.java:369)
        at org.opencb.opencga.storage.core.variant.adaptors.VariantDBAdaptor.getReturnedStudies(VariantDBAdaptor.java:311)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.checkSamplesPermissions(VariantStorageManager.java:396)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.secure(VariantStorageManager.java:356)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.get(VariantStorageManager.java:219)
        at org.opencb.opencga.server.rest.StudyWSServer.getVariants(StudyWSServer.java:496)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.opencb.opencga.server.CORSFilter.doFilter(CORSFilter.java:31)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.getMetaReplicaNodes(ZooKeeperWatcher.java:395)
        at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:562)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1192)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1159)
        at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:300)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:156)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
        ... 69 more

```

**Comment by dnafault** [comment]
HBase/Zookeeper configuration issue.
