### ISSUE TITLE
Error annotating variants - No runners but queue with 16 items!

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#518]
OpenCGA version: 1.0.0-rc3
Cellbase version: v4.5.0-beta (my own instance)

I ran the following command line operation to annotate variants:

`./opencga-analysis.sh variant annotate -o /home/philip/ga4gh-server-env/cpi_datasets/v2.3/APOSLE_cohort88/APOSLE_cohort88_sg1_snvcalls/opencga2/ -v`

It runs for about 5 minutes and then fails with the following error:

`2017-02-06 10:49:54 [pool-2-thread-4] DEBUG DefaultVariantAnnotationManager:176 - Annotated batch of 200 genomic variants. Time: 5.74s
2017-02-06 10:49:58 [pool-2-thread-4] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-02-06 10:49:58 [pool-2-thread-5] INFO  ProgressLogger:157 - Annotated variants: 92400/219571 42.1%, up to position 10:56330939:C:T
2017-02-06 10:49:57 [pool-2-thread-6] DEBUG DefaultVariantAnnotationManager:176 - Annotated batch of 200 genomic variants. Time: 8.243s
2017-02-06 10:49:58 [pool-2-thread-6] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-02-06 10:49:56 [pool-2-thread-7] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-02-06 10:49:58 [pool-2-thread-5] DEBUG DefaultVariantAnnotationManager:176 - Annotated batch of 200 genomic variants. Time: 9.19s
2017-02-06 10:49:58 [pool-2-thread-5] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-02-06 10:49:58 [main] ERROR VariantAnnotationStorageOperation:160 - Error annotating variants.
java.lang.IllegalStateException: No runners but queue with 16 items!!!
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:491)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:322)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:283)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:195)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:107)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:266)
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:149)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:194)
	at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.annotate(VariantCommandExecutor.java:282)
	at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.execute(VariantCommandExecutor.java:97)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:92)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:31)
org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error annotating variants.
	at org.opencb.opencga.storage.core.manager.variant.operations.VariantAnnotationStorageOperation.annotateVariants(VariantAnnotationStorageOperation.java:162)
	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.annotate(VariantStorageManager.java:194)
	at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.annotate(VariantCommandExecutor.java:282)
	at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.execute(VariantCommandExecutor.java:97)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:92)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:31)
Caused by: java.lang.IllegalStateException: No runners but queue with 16 items!!!
	at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:491)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:322)
	at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:283)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.createAnnotation(DefaultVariantAnnotationManager.java:195)
	at org.opencb.opencga.storage.core.variant.annotation.DefaultVariantAnnotationManager.annotate(DefaultVariantAnnotationManager.java:107)
	at org.opencb.opencga.storage.core.variant.VariantStorageEngine.annotate(VariantStorageEngine.java:266`

There's no indication of what might be causing these errors. Any ideas?

Thanks

**Comment by Philip-Wu** [comment]
running it a second time, worked. Could be some kind of race condition...but will be hard to reproduce..I suppose it can be closed
