### ISSUE TITLE
Concurrent table modification error when loading in Hadoop with merge=basic 

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#709]
Loading multiple files with `--merge basic`
Affected version: **release-1.2.0-emr-5.8.0**

```
2017-09-29 10:25:29 [main] ERROR HadoopVariantStorageEngine:254 - Error loading file file:///home/hadoop/hadoop/hadoop/transformed/platinum-genomes-vcf-NA12878_S1.genome.vcf.gz.variants.avro.gz
org.opencb.opencga.storage.core.exceptions.StorageEngineException: Unable to create Phoenix Indexes
        at org.opencb.opencga.storage.hadoop.variant.AbstractHadoopVariantStoragePipeline.registerLoadedFiles(AbstractHadoopVariantStoragePipeline.java:756)
        at org.opencb.opencga.storage.hadoop.variant.HadoopMergeBasicVariantStoragePipeline.postLoad(HadoopMergeBasicVariantStoragePipeline.java:225)
        at org.opencb.opencga.storage.core.StorageEngine.loadFile(StorageEngine.java:124)
        at org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine.lambda$index$1(HadoopVariantStorageEngine.java:210)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ERROR 1070 (44A01): Only tables may be declared as transactional. tableName=OPENCGA_HADOOP_USER_PLATINUM_FULL_A_PF_EXAC_ALL2_A_PF_EXAC_ALL1_IDX
        at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:483)
        at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:150)
        at org.apache.phoenix.schema.MetaDataClient.createTableInternal(MetaDataClient.java:1956)
        at org.apache.phoenix.schema.MetaDataClient.createIndex(MetaDataClient.java:1587)
        at org.apache.phoenix.compile.CreateIndexCompiler$1.execute(CreateIndexCompiler.java:85)
        at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:393)
        at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:376)
        at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:374)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:363)
        at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1707)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.PhoenixHelper.execute(PhoenixHelper.java:73)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.PhoenixHelper.execute(PhoenixHelper.java:67)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.PhoenixHelper.createIndexes(PhoenixHelper.java:206)
        at org.opencb.opencga.storage.hadoop.variant.AbstractHadoopVariantStoragePipeline.registerLoadedFiles(AbstractHadoopVariantStoragePipeline.java:752)
```

```
2017-09-29 10:24:29 [main] ERROR HadoopVariantStorageEngine:254 - Error loading file file:///home/hadoop/hadoop/hadoop/transformed/platinum-genomes-vcf-NA12877_S1.genome.vcf.gz.variants.avro.gz
org.opencb.opencga.storage.core.exceptions.StorageEngineException: Unable to create Phoenix Indexes
        at org.opencb.opencga.storage.hadoop.variant.AbstractHadoopVariantStoragePipeline.registerLoadedFiles(AbstractHadoopVariantStoragePipeline.java:756)
        at org.opencb.opencga.storage.hadoop.variant.HadoopMergeBasicVariantStoragePipeline.postLoad(HadoopMergeBasicVariantStoragePipeline.java:225)
        at org.opencb.opencga.storage.core.StorageEngine.loadFile(StorageEngine.java:124)
        at org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine.lambda$index$1(HadoopVariantStorageEngine.java:210)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.phoenix.exception.PhoenixIOException: org.apache.phoenix.exception.PhoenixIOException: Failed after attempts=36, exceptions:
Fri Sep 29 10:23:52 UTC 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=60102: Call to ip-10-12-82-168.eu-west-2.compute.internal/10.12.82.168:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallT

        at org.apache.phoenix.util.ServerUtil.parseServerException(ServerUtil.java:116)
        at org.apache.phoenix.iterate.BaseResultIterators.getIterators(BaseResultIterators.java:875)
        at org.apache.phoenix.iterate.BaseResultIterators.getIterators(BaseResultIterators.java:819)
        at org.apache.phoenix.iterate.ConcatResultIterator.getIterators(ConcatResultIterator.java:50)
        at org.apache.phoenix.iterate.ConcatResultIterator.currentIterator(ConcatResultIterator.java:97)
        at org.apache.phoenix.iterate.ConcatResultIterator.next(ConcatResultIterator.java:117)
        at org.apache.phoenix.iterate.BaseGroupedAggregatingResultIterator.next(BaseGroupedAggregatingResultIterator.java:64)
        at org.apache.phoenix.iterate.UngroupedAggregatingResultIterator.next(UngroupedAggregatingResultIterator.java:39)
        at org.apache.phoenix.compile.PostLocalIndexDDLCompiler$1.execute(PostLocalIndexDDLCompiler.java:100)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl.updateData(ConnectionQueryServicesImpl.java:3379)
        at org.apache.phoenix.query.DelegateConnectionQueryServices.updateData(DelegateConnectionQueryServices.java:147)
        at org.apache.phoenix.schema.MetaDataClient.buildIndex(MetaDataClient.java:1318)
        at org.apache.phoenix.schema.MetaDataClient.createIndex(MetaDataClient.java:1615)
        at org.apache.phoenix.compile.CreateIndexCompiler$1.execute(CreateIndexCompiler.java:85)
        at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:393)
        at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:376)
        at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:374)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:363)
        at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1707)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.PhoenixHelper.execute(PhoenixHelper.java:73)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.PhoenixHelper.execute(PhoenixHelper.java:67)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.PhoenixHelper.createIndexes(PhoenixHelper.java:206)
        at org.opencb.opencga.storage.hadoop.variant.index.phoenix.VariantPhoenixHelper.createVariantIndexes(VariantPhoenixHelper.java:377)
        at org.opencb.opencga.storage.hadoop.variant.AbstractHadoopVariantStoragePipeline.registerLoadedFiles(AbstractHadoopVariantStoragePipeline.java:754)
        ... 7 more
Caused by: java.util.concurrent.ExecutionException: org.apache.phoenix.exception.PhoenixIOException: Failed after attempts=36, exceptions:
Fri Sep 29 10:23:52 UTC 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=60102: Call to ip-10-12-82-168.eu-west-2.compute.internal/10.12.82.168:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallT

        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.apache.phoenix.iterate.BaseResultIterators.getIterators(BaseResultIterators.java:870)
        ... 30 more
Caused by: org.apache.phoenix.exception.PhoenixIOException: Failed after attempts=36, exceptions:
Fri Sep 29 10:23:52 UTC 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=60102: Call to ip-10-12-82-168.eu-west-2.compute.internal/10.12.82.168:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallT

        at org.apache.phoenix.util.ServerUtil.parseServerException(ServerUtil.java:116)
        at org.apache.phoenix.iterate.TableResultIterator.next(TableResultIterator.java:147)
        at org.apache.phoenix.iterate.LookAheadResultIterator$1.advance(LookAheadResultIterator.java:47)
        at org.apache.phoenix.iterate.LookAheadResultIterator.init(LookAheadResultIterator.java:59)
        at org.apache.phoenix.iterate.LookAheadResultIterator.peek(LookAheadResultIterator.java:73)
        at org.apache.phoenix.iterate.ParallelIterators$1.call(ParallelIterators.java:126)
        at org.apache.phoenix.iterate.ParallelIterators$1.call(ParallelIterators.java:111)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.phoenix.job.JobManager$InstrumentedJobFutureTask.run(JobManager.java:183)
        ... 3 more
```

**Comment by j-coll** [comment]
Fixed at e139753baabbf7431363d63c386fd604ef9b5cca
