### ISSUE TITLE
WriteError with code 11000 does not match with the pattern

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#789]
I think this might be related to #766, while running the variant index pipeline (built from the opencga-1.3-rc at commit 358a4326f091016bdeb5206893f11d14a7766f67) I see the following error:

```
2018-02-11 18:00:11 [pool-1-thread-9] ERROR MongoDBVariantStageLoader:192 - WriteError with code 11000 does not match with the pattern ^.*dup key: \{ : "([^"]*)" \}$
2018-02-11 18:00:11 [pool-1-thread-9] ERROR ParallelTaskRunner:830 - Error writing batch 38209
com.mongodb.MongoBulkWriteException: Bulk write operation error on server localhost:27017. Write errors: [BulkWriteError{index=98, code=11000, message='E11000 duplicate key error collection: opencga_gneva_hgi.stage index: _id_ dup key: { : " 2:  76585772::��2
�0', details={ }}].
        at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:176)
        at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:205)
        at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:146)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:188)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
        at com.mongodb.Mongo.execute(Mongo.java:845)
        at com.mongodb.Mongo$2.execute(Mongo.java:828)
        at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:301)
        at org.opencb.commons.datastore.mongodb.MongoDBNativeQuery.update(MongoDBNativeQuery.java:259)
        at org.opencb.commons.datastore.mongodb.MongoDBCollection.update(MongoDBCollection.java:404)
        at org.opencb.opencga.storage.mongodb.variant.load.stage.MongoDBVariantStageLoader.updateMongo(MongoDBVariantStageLoader.java:168)
        at org.opencb.opencga.storage.mongodb.variant.load.stage.MongoDBVariantStageLoader.insert(MongoDBVariantStageLoader.java:102)
        at org.opencb.opencga.storage.mongodb.variant.load.stage.MongoDBVariantStageLoader.write(MongoDBVariantStageLoader.java:93)
        at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:828)
        at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:811)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by j-coll** [comment]
Hi @nicholsn .

You are correct, this is the same issue as #766.

As I see, the compilation that you are using does not contain the fix that was made to solve the bug. It was solved the 5th of January (a67102b29aa8ca9994604a2003e50e5a28b5363c), and you are using a version from the 23rd of November.

I would suggest to upgrade your OpenCGA installation to the latest version, [v1.3.2](https://github.com/opencb/opencga/releases/tag/v1.3.2).
