### ISSUE TITLE
ERROR VariantFileIndexerStorageOperation:809 - This code should never be executed

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#798]
I had a run of the variant index pipeline fail during the merge stage due to a memory allocation error leading to a coredump, and when I try to resume the pipeline I receive the error below. This is the command I am submitting:

```
./opencga-analysis.sh variant index \
    --file $WGS_FILE \
    --outdir $WORK_DIR \
    --calculate-stats \
    --annotate \
    --annotator cellbase_db_adaptor \
    -s $STUDY \
    -S $TOKEN \
    --load \
    --transformed-files $TRANSFORMED_FILE \
    --resume
```

I am running v1.3.2 at commit 55dffdf5d37de77bd651e1730a86c2036fa148d8.

```
2018-02-18 08:24:47 [main] ERROR VariantFileIndexerStorageOperation:809 - This code should never be executed. Every vcf file containing the transformed status should have a registered transformed file
org.opencb.opencga.catalog.exceptions.CatalogException: Internal error. No transformed file could be found for file 4804
        at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.getTransformedFromOriginal(VariantFileIndexerStorageOperation.java:811)
        at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.filterLoadFiles(VariantFileIndexerStorageOperation.java:746)
        at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.index(VariantFileIndexerStorageOperation.java:220)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:176)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:167)
        at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:269)
        at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:102)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
```

**Comment by j-coll** [comment]
Hi @nicholsn , 

Reading the stack trace, I see that it does not match with the version and commit that you pointed. Actually, it matches with the one that you were using in #789, the https://github.com/opencb/opencga/commit/358a4326f091016bdeb5206893f11d14a7766f67.

Is it possible that you didn't restart the daemon or missed any step when upgrading opencga?

**Comment by nicholsn** [comment]
The initial run was under the previous commit, but I tried to resubmit using the latest version. I ended up deleting the file, relinking, and starting the pipeline over with a proper amount of memory. Will let you know if this pops up again
