### ISSUE TITLE
Unable to parse genotype

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#845]
I'm running into a parsing error for a vcf file processed using GATK based on the [ADNI](http://adni.loni.usc.edu/) dataset.

Is this expected to fail at the transform stage? Any suggestions on how to patch this? 

```
2018-05-29 20:09:26 [pool-1-thread-3] ERROR ParallelTaskRunner:629 - Error processing batch 1847
java.lang.IllegalArgumentException: Unable to parse genotype ''. Empty allele: REF=T,ALT=C
        at org.opencb.biodata.models.feature.Genotype.parseGenotype(Genotype.java:129)
        at org.opencb.biodata.models.feature.Genotype.<init>(Genotype.java:71)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.getBuilder(VariantContextToVariantConverter.java:230)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:99)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:89)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:45)
        at org.opencb.biodata.tools.Converter.apply(Converter.java:41)
        at org.opencb.opencga.storage.core.variant.transform.VariantTransformTask.apply(VariantTransformTask.java:176)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-05-29 20:09:26 [pool-1-thread-3] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2018-05-29 20:09:26 [pool-1-thread-4] ERROR ParallelTaskRunner:629 - Error processing batch 1848
java.lang.IllegalArgumentException: Unable to parse genotype ''. Empty allele: REF=TCTC,ALT=T
        at org.opencb.biodata.models.feature.Genotype.parseGenotype(Genotype.java:129)
        at org.opencb.biodata.models.feature.Genotype.<init>(Genotype.java:71)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.getBuilder(VariantContextToVariantConverter.java:230)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:99)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:89)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:45)
        at org.opencb.biodata.tools.Converter.apply(Converter.java:41)
        at org.opencb.opencga.storage.core.variant.transform.VariantTransformTask.apply(VariantTransformTask.java:176)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-05-29 20:09:26 [pool-1-thread-4] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2018-05-29 20:09:26 [pool-1-thread-5] WARN  ParallelTaskRunner:752 - Abort writing thread on fail
2018-05-29 20:09:26 [pool-1-thread-1] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2018-05-29 20:09:27 [main] WARN  ParallelTaskRunner:538 - Abort read thread on fail
2018-05-29 20:09:27 [pool-1-thread-2] ERROR ParallelTaskRunner:629 - Error processing batch 1849
java.lang.IllegalArgumentException: Unable to parse genotype ''. Empty allele: REF=G,ALT=A
        at org.opencb.biodata.models.feature.Genotype.parseGenotype(Genotype.java:129)
        at org.opencb.biodata.models.feature.Genotype.<init>(Genotype.java:71)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.getBuilder(VariantContextToVariantConverter.java:230)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:99)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:89)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:45)
        at org.opencb.biodata.tools.Converter.apply(Converter.java:41)
        at org.opencb.opencga.storage.core.variant.transform.VariantTransformTask.apply(VariantTransformTask.java:176)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-05-29 20:09:27 [pool-1-thread-2] WARN  ParallelTaskRunner:641 - Abort task thread on fail
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:418 - read:  timeReading                  = 64.263s
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:419 - read:  timeBlockedAtPutRead         = 0.016s
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:420 - task;  timeBlockedAtTakeRead        = 430.765s(total)   ~107.691s/thread
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:424 - task;  timeTaskApply                = 1507.995s(total)   ~376.998s/thread
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:428 - task;  timeBlockedAtPutWrite        = 0.019s(total)   ~0.004s/thread
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:430 - write: timeBlockedWatingDataToWrite = 14.802s
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:431 - write: timeWriting                  = 469.634s
2018-05-29 20:09:27 [main] INFO  ParallelTaskRunner:434 - total:                              = 485.714s
2018-05-29 20:09:27 [main] ERROR VariantFileIndexerStorageOperation:282 - Error executing INDEX
org.opencb.opencga.storage.core.exceptions.StoragePipelineException: Exception executing transform.
        at org.opencb.opencga.storage.core.StorageEngine.transformFile(StorageEngine.java:153)
        at org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine.index(MongoDBVariantStorageEngine.java:289)
        at org.opencb.opencga.storage.core.manager.variant.operations.VariantFileIndexerStorageOperation.index(VariantFileIndexerStorageOperation.java:280)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:178)
        at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:169)
        at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:293)
        at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:112)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
        at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
Caused by: org.opencb.opencga.storage.core.exceptions.StorageEngineException: Error while executing TransformVariants in ParallelTaskRunner
        at org.opencb.opencga.storage.core.variant.VariantStoragePipeline.transform(VariantStoragePipeline.java:374)
        at org.opencb.opencga.storage.core.StorageEngine.transformFile(StorageEngine.java:145)
        ... 8 more
Caused by: java.util.concurrent.ExecutionException: Error while running ParallelTaskRunner. Found 3 exceptions.
        at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:438)
        at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:297)
        at org.opencb.opencga.storage.core.variant.VariantStoragePipeline.transform(VariantStoragePipeline.java:372)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: Unable to parse genotype ''. Empty allele: REF=T,ALT=C
        at org.opencb.biodata.models.feature.Genotype.parseGenotype(Genotype.java:129)
        at org.opencb.biodata.models.feature.Genotype.<init>(Genotype.java:71)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.getBuilder(VariantContextToVariantConverter.java:230)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:99)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:89)
        at org.opencb.biodata.tools.variant.converters.avro.VariantContextToVariantConverter.convert(VariantContextToVariantConverter.java:45)
        at org.opencb.biodata.tools.Converter.apply(Converter.java:41)
        at org.opencb.opencga.storage.core.variant.transform.VariantTransformTask.apply(VariantTransformTask.java:176)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:627)
        at org.opencb.commons.run.ParallelTaskRunner$TaskRunnable.call(ParallelTaskRunner.java:594)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by nicholsn** [comment]
sure, will send offline

**Comment by j-coll** [comment]
The error due to the alternate `*` that represent a deletion of the reference allele for that individual. This feature is not yet supported.

See: #410
