### ISSUE TITLE
 Read timed out --genotype 

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#889]
Hi Team,

We are getting **Read timeout** error on running below command in opencga shell.Please help!

**Command:**
./opencga.sh variant query --study reference_grch37:1kG_phase3 --genotype "NA19030:0|1,1|0,1|1;NA19043:0|1,1|0,1|1" --limit 3 --exclude studies

**Error:**
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

Is this query being executed against HGVA? I am executing now the same command without any issue.

Probably there was a temporary performance degradation due to an internal maintenance operation in the servers.

Please, let me know if you still have problems. If so, please write the time and date of the query to check the logs.

**Comment by Mohammedhusen** [comment]
Hi Thanks for your response.

Query work fine after changing | (pipe line) to / (forward slash).

Old Query:
./opencga.sh variant query --study reference_grch37:1kG_phase3 --genotype "NA19030:0|1,1|0,1|1;NA19043:0|1,1|0,1|1" --limit 3 --exclude studies
New query:
./opencga.sh variant query --study reference_grch37:1kG_phase3 --genotype "NA19030:0/1,1|0,1/1;NA19043:0/1,1/0,1/1" --limit 3 --exclude studies.
